Section "OutputClass"
	Identifier      "LoongGPU"
	MatchDriver     "loonggpu"
	Driver          "modesetting"
	Option          "GlxVendorLibrary"         "loonggpu"
	Option          "SWcursor"                 "false"
EndSection
