.TH RATPOINTS "1" "May 2012" "ratpoints 2.1.3" "User Commands"
.SH NAME
ratpoints \- manual page for ratpoints 2.1.3
.SH SYNOPSIS
.B ratpoints
\fI'a_0 a_1 \fR... \fIa_n' max_height\fR ...
.SH OPTIONS
[\-dl low_den] [\-du up_den]
[\-f format] [\-fs str] [\-fm str] [\-fe str] [\-y] [\-Y]
[[\-l low1] \fB\-u\fR up1 ... \fB\-l\fR lown [\-u upn]]
[\-n num_primes1] [\-N num_primes2] [\-p max_primes]
[\-F max_forbidden] [\-s] [\-S [iter]]
[\-q] [\-v] [\-z] [\-Z] [\-1] [\-i] [\-I]
[\-k] [\-K] [\-j] [\-J] [\-x] [\-X]
.SH COPYRIGHT
This is ratpoints\-2.1.3 Copyright (C) 2008,2009 by Michael Stoll.
.PP
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under the
terms of the GNU General Public License version 2 or later.
.PP
Please acknowledge use of this program in published work.
.IP
.SH "SEE ALSO"
The full documentation for
.B ratpoints
is installed at
.I /usr/share/doc/ratpoints-2.1.3/ratpoints-doc.pdf
