[server]
# The directory where PlayStation 3 content are stored
root = /srv/ps3netsrv-go
# Optional client IP whitelist. 
# Formats: 
#   single IPv4/v6 ('192.168.0.2')
#   IPv4/v6 CIDR ('192.168.0.1/24') 
#   IPv4 + subnet mask ('192.168.0.1/255.255.255.0) 
#   IPv4/IPv6 range ('192.168.0.1-192.168.0.255')
client-whitelist = 0.0.0.0/0
# Limit amount of connected clients. Negative or zero means no limit.
max-clients = 10
# Allow writing/modifying filesystem operations.
allow-write = true
