# Scroll emulation for GPD Pocket 4

Section "InputClass"
    Identifier "GPD Pocket 4 Touchpad"
    MatchProduct "HAILUCK CO.,LTD USB KEYBOARD Mouse"
    Driver "libinput"
    Option "ScrollMethod" "button"
    Option "ScrollButton" "2"
EndSection
