instance_name = "default"
dhcp = false
listeners = [
    "tcp://0.0.0.0:11010",
    "udp://0.0.0.0:11010",
    "wg://0.0.0.0:11011",
    "ws://0.0.0.0:11011/",
    "wss://0.0.0.0:11012/",
]
mapped_listeners = []
exit_nodes = []
peer = []
rpc_portal = "0.0.0.0:0"

[network_identity]
network_name = "default"
network_secret = ""

[flags]
