name: 'Security Vulnerabilities Report'
description: 'Any security vulnerabilities report should be filed with this template.'
labels: ['security']
body:
- type: input
  attributes:
    label: 'CVE IDs'
    description: 'Comma-separated list of CVE IDs.'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Other security advisory IDs'
    description: 'Other security advisory IDs. Please list with references to each ID.'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Description'
    description: 'Original mailing list message(s) or other description here.'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Patches'
    description: 'Enter "N/A" if version update is preferred, otherwise please label each patch with ref. to original vulnerability ID(s).'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'PoC(s)'
    description: 'Please list links to available PoCs (Proofs of Concept).'
  validations:
    required: true
- type: input
  attributes:
    label: 'Topic PR'
    description: 'Please input topic pull request number here.'
  validations:
    required: true
