#!/bin/bash

printf "$(cat << EOF
FFFFFFFFFFFFFFFFFFFFFF                                  kkkkkkkk            !!!
F::::::::::::::::::::F                                  k::::::k           !!:!!
F::::::::::::::::::::F                                  k::::::k           !:::!
FF::::::FFFFFFFFF::::F                                  k::::::k           !:::!
  F:::::F       FFFFFF ssssssssss       cccccccccccccccc k:::::k    kkkkkkk!:::!
  F:::::F            ss::::::::::s    cc:::::::::::::::c k:::::k   k:::::k !:::!
  F::::::FFFFFFFFFFss:::::::::::::s  c:::::::::::::::::c k:::::k  k:::::k  !:::!
  F:::::::::::::::Fs::::::ssss:::::sc:::::::cccccc:::::c k:::::k k:::::k   !:::!
  F:::::::::::::::F s:::::s  ssssss c::::::c     ccccccc k::::::k:::::k    !:::!
  F::::::FFFFFFFFFF   s::::::s      c:::::c              k:::::::::::k     !:::!
  F:::::F                s::::::s   c:::::c              k:::::::::::k     !!:!!
  F:::::F          ssssss   s:::::s c::::::c     ccccccc k::::::k:::::k     !!!
FF:::::::FF        s:::::ssss::::::sc:::::::cccccc:::::ck::::::k k:::::k
F::::::::FF        s::::::::::::::s  c:::::::::::::::::ck::::::k  k:::::k   !!!
F::::::::FF         s:::::::::::ss    cc:::::::::::::::ck::::::k   k:::::k !!:!!
FFFFFFFFFFF          sssssssssss        cccccccccccccccckkkkkkkk    kkkkkkk !!!
EOF
)\n"
