# Begin /etc/nsswitch.conf

passwd: files systemd
group: files systemd
shadow: files systemd

hosts: files mdns_minimal [NOTFOUND=return] dns resolve
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
