for i in /etc/X11/xinit/xinitrc.d/*; do
    source $i
done

source ~/.xprofile

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
xscreensaver &
sh /usr/share/cwallpaper/makeList.sh /usr/share/wallpapers && \
    cwallpaper -l &
exec icewm-session
