security = true

[name]
default = "7-Zip 25.01"
zh_CN = "7-Zip 25.01"

[caution]
default = "Fixes an arbitrary file write vulnerability on extraction that may lead to code execution - CVE-2025-55188 (Severity: Low)"
zh_CN = "修复一处解压时可能导致任意文件写入并可进而触发代码执行的漏洞，漏洞编号 CVE-2025-55188（严重性：低）"

[packages]
"7-zip" = "25.01"
