security = true

[name]
default = "7-Zip 26.02"

[caution]
default = "Fix a Heap-based Buffer Overflow vulnerability when processing XZ chunked data (CVE-2026-14266, Severity: High)"
zh_CN = "修复处理 XZ 压缩数据时的一个堆缓冲区溢出漏洞（漏洞编号 CVE-2026-14266，严重性：高）"

[packages-v2]
"7-zip" = "< 26.02"
