security = true

[name]
default = "AIDE 0.19.2"
zh_CN = "AIDE 0.19.2"

[caution]
default = "Fixes an improper output neutralization vulnerability - CVE-2025-54389 (Severity: Medium); Fixes a null pointer dereference vulnerability - CVE-2025-54409 (Severity: Medium)"
zh_CN = "修复一处输出无害化处理不当漏洞，漏洞编号 CVE-2025-54389（严重性：中）；修复一处空指针解引用漏洞，漏洞编号 CVE-2025-54409（严重性：中）"

[packages]
"aide" = "0.19.2"
