security = true

[name]
default = "aiohttp 3.14.1"

[caution]
default = "Fixes a Deserialization of Untrusted Data vulnerability (CVE-2026-34993, Severity: High) and an Origin Validation Error vulnerability (CVE-2026-47265, Severity: High)"
zh_CN = "修复一个不可信数据反序列化漏洞（漏洞编号 CVE-2026-34993，严重性：高）和一个来源验证错误漏洞（漏洞编号 CVE-2026-47265，严重性：高）"

[packages-v2]
"aiohttp" = "< 3.14.1"
