security = true
must_match_all = false

[name]
default = "amo 0.6.0"

[caution]
default = "Fixes an Authorization Bypass via PID Reuse vulnerability in zbus_polkit < 5.1.0 (RUSTSEC-2026-0278, Severity: High)"
zh_CN = "修复 zbus_polkit < 5.1.0 中一个通过复用 PID 实现的提权绕过漏洞（RUSTSEC-2026-0278，严重性：高）"

[packages-v2]
"amo" = "< 0.6.0"
