security = true

[name]
default = "Apache Arrow 23.0.1"

[caution]
default = "Fixes a Use-After-Free vulnerability - CVE-2026-25087 (Severity: High)"
zh_CN = "修复一个释放后使用 (Use-After-Free) 漏洞，漏洞编号 CVE-2026-25087（严重性：高）"

[packages-v2]
"apache-arrow" = "< 23.0.1"
