security = true

[name]
default = "assimp 6.0.4"

[caution]
default = "Fixes 10 security vulnerabilities (including 7 of high severity and 3 of medium severity)"
zh_CN = "修复 10 处安全漏洞（含 7 个高危漏洞, 3 个中危漏洞）"

[packages-v2]
"assimp" = "< 6.0.4"
