security = true

[name]
default = "Bind 9.20.29"

[caution]
default = "Fixes 14 security vulnerabilities (including 7 of High, and 7 of Medium severity)"
zh_CN = "修复 14 个安全漏洞（含 7 个高危漏洞和 7 个中危漏洞）"

[packages-v2]
"bind" = "< 1:9.20.29"
