security = true

[name]
default = "Bind 9.20.23"

[caution]
default = "Fixes 10 security vulnerabilities (including 1 of Critical, 5 of High, and 4 of Medium severity)"
zh_CN = "修复 10 个安全漏洞（含 1 个严重漏洞、5 个高危漏洞和 4 个中危漏洞）"

[packages-v2]
"bind" = "< 9.20.23"
