security = true

[name]
default = "BIND 9.20.18"

[caution]
default = "Fixes a vulnerability where malformed BRID/HHIT records can cause named(8) to terminate unexpectedly - CVE-2025-13878 (Severity: High)"
zh_CN = "修复安全漏洞：畸形 BRID/HHIT 记录可能导致 named(8) 程序异常终止，漏洞编号 CVE-2025-13878（严重性：高）"

[packages-v2]
"bind" = "< 1:9.20.18"
