security = true

[name]
default = "Botan 3.11.1"

[caution]
default = "Fixes a heap over-read vulnerability - CVE-2026-32877 (severity: High), a vulnerability that omitted verifying the signature of the OCSP response - CVE-2026-32883 (severity: Medium) and a Name Constraints bypass vulnerability - CVE-2026-32884 (severity: Medium) "
zh_CN = "修复一个堆溢出漏洞（漏洞编号 CVE-2026-32877，严重性：高），一个因未验证 OCSP 响应签名导致的漏洞（漏洞编号 CVE-2026-32883，严重性：中）和一个名称约束绕过漏洞（漏洞编号 CVE-2026-32884，严重性：中）"

[packages-v2]
"botan" = "< 3.11.1"
