security = true

[name]
default = "Botan 3.12.0"

[caution]
default = "Fixes an Inefficient Algorithmic Complexity vulnerability (CVE-2026-44378, Severity: High)"
zh_CN = "修复 1 个算法复杂度不当漏洞（漏洞编号 CVE-2026-44378，严重性：高）"

[packages-v2]
"botan" = "< 3.12.0"
