security = true

[name]
default = "Bubblewrap 0.12.0"

[caution]
default = "Fixes a Path Traversal/Link Following vulnerability (Severity: High)"
zh_CN = "修复一个路径遍历/路径跟随漏洞（严重性：高）"

[packages-v2]
"bubblewrap" = "< 0.12.0"
