security = true

[name]
default = "BusyBox 1.37.0 Security Update"
zh_CN = "BusyBox 1.37.0 安全更新"

[caution]
default = "Fixes a TOCTOU (Time-Of-Check to Time-of-Use) race condition vulnerability (severity: high)"
zh_CN = "修复一处 TOCTOU（检查到使用时间）竞态条件漏洞（严重性：高）"

[packages]
"busybox" = "1.37.0-1"
