security = true

[name]
default = "BusyBox 1.38.0"

[caution]
default = "Fixes an UI Misrepresentation of Critical Information vulnerability (CVE-2025-46394, Severity: Low) and an Improper Access Control vulnerability (CVE-2025-60876, Severity: Medium)"
zh_CN = "修复一个 UI 错误展示重要信息的漏洞（CVE-2023-39810，严重性：高）和一个访问控制不恰当漏洞（CVE-2025-60876，严重性：中）"

[packages-v2]
"busybox" = "< 1.38.0"
