security = true

[name]
default = "CairoSVG 2.9.0"

[caution]
default = "Fixes an Uncontrolled Recursion vulnerability (CVE-2026-31899, Severity: High)"
zh_CN = "修复一个未经控制的递归漏洞（CVE-2026-31899，严重性：高）"

[packages-v2]
"cairosvg" = "< 2.9.0"
