security = true

[name]
default = "Calibre 9.5.0"

[caution]
default = "Fixes a path traversal vulnerabilities (CVE-2026-30853, Severity: High)"
zh_CN = "修复一个路径穿越漏洞，漏洞编号CVE-2026-30853（严重性：高）"

[packages-v2]
"calibre" = "< 9.5.0"
