security = true

[name]
default = "Calibre 9.4.0"

[caution]
default = "Fixes 7 security vulnerabilities (including 2 of critical severity, 3 of high severity and 2 of medium severity)"
zh_CN = "修复 7 处安全漏洞（含 2 个严重漏洞、3 个高危漏洞和 2 个中危漏洞）"

[packages-v2]
"calibre" = "< 9.4.0"
