security = true

[name]
default = "Calibre 9.6.0"

[caution]
default = "Fixes a Server-Side Request Forgery vulnerability - CVE-2026-33205 (severity: High) and a Path Traversal vulnerability - CVE-2026-33206 (severity: High) "
zh_CN = "修复一个服务端请求伪造漏洞，漏洞编号 CVE-2026-33205（严重性：高）和一个路径穿越漏洞，漏洞编号 CVE-2026-33206（严重性：高）"

[packages-v2]
"calibre" = "< 9.6.0"
