security = true

[name]
default = "Cap'n Proto 1.4.0"

[caution]
default = "Fixes 2 HTTP request/response smuggling vulnerabilities - CVE-2026-32239, CVE-2026-32240 (Severity: Medium)"
zh_CN = "修复两个 HTTP 请求响应走私漏洞，漏洞编号 CVE-2026-32239、CVE-2026-32240（严重性：中）"

[packages-v2]
"capnproto" = "< 1.4.0"
