security = true

[name]
default = "Cap'n Proto 1.3.0"

[caution]
default = "Fixes a out-of-bounds read vulnerabilities - CVE-2022-46149 (Severity: Medium)"
zh_CN = "修复一个越界读取漏洞，漏洞编号 CVE-2022-46149（严重性：中）"

[packages-v2]
"capnproto" = "< 1.3.0"
