security = true

[name]
default = "Chromium 135.0.7049.95"

[caution]
default = "Fixes 2 security vulnerabilities (1 each of critical and high severities)"
zh_CN = "修复 2 个安全漏洞（含 1 个严重漏洞，1 个高危漏洞）"

[packages]
"chromium" = "135.0.7049.95"
