security = true

[name]
default = "Clash Verge Service Security Update"
zh_CN = "Clash Verge 服务安全更新"

[caution]
default = "Fixes a remote code execution vulnerability exploitable via parameter manipulation"
zh_CN = "修复一处可通过操纵程序参数利用的远程代码执行漏洞"

[packages]
"clash-verge-service" = "0+git20250324-2"
