security = true

[name]
default = "Clash Verge Service (IPC) 2.3.0, Revision 1"
zh_CN = "Clash Verge 服务 (IPC) 2.3.0，修订 1"

[caution]
default = "Mitigates an Execution with Unnecessary Privileges vulnerability, but Denial-of-Service is still possible (a vairant of CVE-2025-50505, severity: High)"
zh_CN = "缓解一个使用不必要权限执行的漏洞，但仍可能导致拒绝服务（CVE-2025-50505 的变种，严重性：高）"

[packages-v2]
"clash-verge-service-ipc" = "< 2.3.0-1"
