security = true

[name]
default = "cloud-init 26.1"

[caution]
default = "Fixes an Improper Authentication vulnerability (CVE-2024-6174, Severity: High) and an Incorrect Permission Assignment for Critical Resource vulnerability (CVE-2024-11584, Severity: Medium)"
zh_CN = "修复一个鉴权错误漏洞（CVE-2024-6174，严重性：高）和一个关键资源权限分配错误漏洞（CVE-2024-11584，严重性：中）"

[packages-v2]
"cloud-init" = "< 26.1"
