security = true

[name]
default = "cni-plugins 1.9.0"

[caution]
default = "Fixes an information exposure vulnerability - CVE-2025-67499 (Severity: Moderate)"
zh_CN = "修复一处信息泄露漏洞，漏洞编号 CVE-2025-67499（严重性：中）"

[packages-v2]
"cni-plugins" = ">= 1.6.0 && < 1.9.0"
