security = true

[name]
default = "configobj 5.0.9"

[caution]
default = "Fixes a ReDoS vulnerabilities - CVE-2023-26112 (Severity: Low)"
zh_CN = "修复一个正则表达式拒绝服务攻击漏洞，漏洞编号 CVE-2023-26112（严重性：低）"

[packages-v2]
"configobj" = "< 5.0.9"
