security = true

[name]
default = "confuse 3.4"

[caution]
default = "Fixes an Out-of-bounds Read vulnerability (CVE-2022-40320, Severity: High)"
zh_CN = "修复一个越界读取漏洞（CVE-2022-40320，严重性：高）"

[packages-v2]
"confuse" = "< 3.4"
