security = true

[name]
default = "containerd 2.3.2"

[caution]
default = "Fixes 5 security vulnerabilities (including 3 of Critical, 1 of High, and 1 of Medium severity)"
zh_CN = "修复 5 个安全漏洞（含 3 个严重、1 个高危和 1 个中危漏洞）"

[packages-v2]
"containerd" = "< 2.3.2"
