security = false
must_match_all = false

[name]
default = "AOSC OS Core 13.0.1"
zh_CN = "安同 OS 核心包，版本 13.0.1"

[caution]
default = "Hotfix for application launch failures (runtime) and build-time failure on Loongson 3 (MIPS)"
zh_CN = "针对龙芯三号 (MIPS) 的应用启动失败及构建时错误的紧急修复"

[packages-v2]
"aosc-aaa" = "< 13.0.1"
"gcc" = "< 1:2.42-1"
