security = false
must_match_all = true

[name]
default = "AOSC OS Core 12.2.0"
zh_CN = "安同 OS 核心包，版本 12.2.0"

[caution]
default = "Updates GCC to 14.3.0 and enables support for systemd dynamic users"
zh_CN = "更新 GCC 至 14.3.0 并开启 systemd 动态用户支持"

[packages]
"aosc-aaa" = "12.2.0"
"gcc-runtime" = "14.3.0"
"glibc" = "1:2.40-3"
"linux+api" = "2:6.12.30"
