security = false
must_match_all = false

[name]
default = "AOSC OS Core 13.0.2"
zh_CN = "安同 OS 核心包，版本 13.0.2"

[caution]
default = "Fixes link-time errors when against static GCC libraries, link-time errors on AArch64 hosts when compiler-optimized atomic operations functions (out-of-line atomics) are enabled, as well as potential upgrade errors when attempting to update from preview Core 13 updates"
zh_CN = "修复链接 GCC 静态库时出错的问题及 AArch64 宿主在开启编译器优化的原子操作函数 (out-of-line atomics) 时链接出错的问题，并修复部分 Core 13 预览用户无法完成更新的问题"

[packages-v2]
"aosc-aaa" = "< 13.0.2"
"gcc" = "< 1:15.2.0-1"
