security = false
must_match_all = false

[name]
default = "AOSC OS Core 13.0.0"
zh_CN = "安同 OS 核心包，版本 13.0.0"

[caution]
default = "Updates core runtime and toolchain to the latest versions, including glibc 2.42 and GCC 15, as well as Zlib-ng 2.3.2, with optimization for x86, AArch64, LoongArch, and RISC-V"
zh_CN = "包括 glibc 2.42 及 GCC 15，以及包含 x86、AArch64、龙架构及 RISC-V 优化的 Zlib-ng 2.3.2 等核心运行时及工具链更新"

[packages-v2]
"aosc-aaa" = "< 13.0.0"
"gcc" = "< 1:15.2.0"
"glibc" = "< 1:2.42"
"libxcrypt" = "< 4.5.2"
"linux+api" = "< 2:6.12.50"
"zlib" = "< 1:2.3.2"
