security = true
must_match_all = false

[name]
default = "AOSC OS Core 14.0.0"
zh_CN = "安同 OS 核心包，版本 14.0.0"

[caution]
default = "Updates core runtime and toolchain to the latest versions, including glibc 2.44 and GCC 16, fixes 14 security vulnerabilites disclosed in glibc security advisories GLIBC-SA-2026-0011 through GLIBC-SA-2026-0024 (including 2 of High severity)"
zh_CN = "包括 glibc 2.44 及 GCC 16 的核心运行时及工具链更新，修复 glibc 安全公告 GLIBC-SA-2026-0011 至 GLIBC-SA-2026-0024 中披露的 14 个安全漏洞（含 2 个高危漏洞）"

[packages-v2]
"aosc-aaa" = "< 14.0.0"
"gcc" = "< 1:16.2.0"
"glibc" = "< 1:2.44"
