security = true
must_match_all = false

[name]
default = "Core 13.1.5"

[caution]
default = "Fixes 2 security vulnerabilities disclosed in glibc Security Advisories GLIBC-SA-2026-0005 and GLIBC-SA-2026-0006 (Severity: High) and a GCC 15 internal compiler error building WebKitGTK on AArch64 with -ggdb"
zh_CN = "修复 glibc 第 GLIBC-SA-2026-0005 及第 GLIBC-SA-2026-0006 号安全公告中披露的 2 个安全漏洞（严重性：高）以及 GCC 15 在 AArch64 开启 -ggdb 构建 WebKitGTK 时触发的一项编译器内部错误"

[packages-v2]
"glibc" = "< 1:2.42-4"
"gcc" = "< 15.2.0-5"
