security = true
must_match_all = false # people may not have gcc-15 installed

[name]
default = "AOSC OS Core 13.2.0"
zh_CN = "安同 OS 核心包，版本 13.2.0"

[caution]
default = "Fixes 3 vulnerabilities disclosed in GLIBC-SA-2026-0007, GLIBC-SA-2026-0009, and GLIBC-SA-2026-0010 (1 of critical severity and 2 of high severity), and harden GCC stack protector on LoongArch against an easy bypass"
zh_CN = "修复 glibc 安全公告 GLIBC-SA-2026-0007、GLIBC-SA-2026-0009 及 GLIBC-SA-2026-0010 中披露的 3 个安全漏洞（含 1 个严重漏洞、2 个高危漏洞），并针对龙架构加强 GCC 栈溢出保护以阻止简单的绕过手段"

[packages-v2]
"glibc" = "< 1:2.42-5"
"gcc-15" = "< 15.2.0-7"
