security = true
must_match_all = false

[name]
default = "AOSC OS Core 13.0.6"
zh_CN = "安同 OS 核心包，版本 13.0.6"

[caution]
default = "Fixes an interger overflow vulnerability (severity: High) and a stack memory contents leak vulnerability found in glibc 2.42"
zh_CN = "修复 glibc 2.42 的一处整数溢出漏洞（严重性：高）和一处堆栈内容泄漏漏洞"

[packages-v2]
"aosc-aaa" = "< 13.0.6"
"glibc" = "< 1:2.42-2"
"glibc+32" = "< 2.42"
