security = false
must_match_all = false

[name]
default = "AOSC OS Core 12.1.3"
zh_CN = "安同 OS 核心包，版本 12.1.3"

[caution]
default = "Fixes inconsistent CMake configuration in zlib (zlib-ng), causing some software to fail to build"
zh_CN = "修复 zlib (zlib-ng) 软件包中 CMake 配置与包内文件不一致的问题，该问题先前导致部分软件无法正常构建"

[packages]
"linux+api" = "2:6.12.23"
"zlib" = "1:2.2.4-2"
"aosc-aaa" = "12.1.3"
