security = true

[name]
default = "coturn 4.10.0"

[caution]
default = "Fixes an Incorrect Type Conversion or Cast vulnerability (CVE-2026-40613, Severity: High)"
zh_CN = "修复一个不正确的类型转换漏洞（CVE-2026-40613，严重性：高）"

[packages-v2]
"coturn" = "< 4.10.0"
