security = true

[name]
default = "crun 1.27.1"

[caution]
default = "Fixes a privilege escalation vulnerability (CVE-2026-30892, Severity: High)"
zh_CN = "修复一个提权漏洞（CVE-2026-30892，严重性：高）"

[packages-v2]
"crun" = "< 1.27.1"
