security = true

[name]
default = "Cryptsetup 2.8.6"

[caution]
default = "Fixes the unintended kernel keyring leak vulnerability in LUKS subcommands"
zh_CN = "修复 LUKS 子命令中非预期的内核密钥环泄漏漏洞"

[packages-v2]
cryptsetup = "< 2.8.6"
