security = true

[name]
default = "PyCA cryptography 46.0.7"

[caution]
default = "Fixes a Buffer Overflow vulnerability - CVE-2026-39892 (Severity: High)"
zh_CN = "修复一个缓冲区溢出漏洞，漏洞编号 CVE-2026-39892（严重性：高）"

[packages-v2]
"cryptography" = "< 46.0.7"
