security = true
must_match_all = false

[name]
default = "CUPS 2.4.19"
zh_CN = "CUPS 2.4.19"

[caution]
default = "Fixes an out-of-bounds read vulnerability - CVE-2026-41079 (Severity: Medium)"
zh_CN = "修复一个越界读取 (Out-of-bounds Read) 漏洞（CVE-2026-41079，严重性：中）"

[packages-v2]
"cups" = "< 2.4.19"
"cups+32" = "< 2.4.19"
