security = true

[name]
default = "CUPS Printing System 2.4.17"
zh_CN = "CUPS 打印系统 2.4.17"

[caution]
default = "Fixes 8 security vulnerabilities (2 of high severity, 5 of medium severity)"
zh_CN = "修复 8 个安全漏洞（含 2 个高危漏洞、5 个中危漏洞）"

[packages-v2]
"cups" = "< 2.4.17"
