security = true
must_match_all = false

[name]
default = "CUPS Printing System 2.4.13"
zh_CN = "CUPS 打印系统 2.4.13"

[caution]
default = "Fixes two security vulnerabilities - CVE-2025-58060, CVE-2025-58364 (one of critical severity)"
zh_CN = "修复两个安全漏洞，漏洞编号 CVE-2025-58060, CVE-2025-58364（含一个严重漏洞）"

[packages]
"cups" = "2.4.13"
"cups+32" = "2.4.13"
