security = true
must_match_all = false

[name]
default = "curl 8.19.0"

[caution]
default = "Fixes 3 security vulnerabilities (including 1 of High severity and 2 Medium)"
zh_CN = "修复 3 个安全漏洞（含 1 个高危漏洞和 2 个中危漏洞）"

[packages-v2]
"curl" = "< 8.19.0"
"curl+32" = "< 8.19.0"
