security = true

[name]
default = "curl 8.16.0"

[caution]
default = "Fixes a out-of-bound cookie path read vulnerability - CVE-2025-9086 (Severity: Low), and a predictable WebSocket mask vulnerability - CVE-2025-10148 (Severity: Low)"
zh_CN = "修复一处 Cookie 越界读取 (Out-of-bound cookie path read) 漏洞，漏洞编号 CVE-2025-9086（严重性：低），及一处可预测 WebSocket 掩码漏洞，漏洞编号 CVE-2025-10148（严重性：低）"
zh_TW = "修復一處 Cookie 越界讀取 (Out-of-bound cookie path read) 漏洞，漏洞編號 CVE-2025-9086（嚴重性：低），及一處可預測 WebSocket 遮罩漏洞，漏洞編號 CVE-2025-10148（嚴重性：低）"

[packages]
"curl" = "8.16.0"
