security = true
must_match_all = false

[name]
default = "curl 8.21.0"

[caution]
default = "Fixes 18 security vulnerabilities (including 4 of Medium severity)"
zh_CN = "修复 18 个安全漏洞（含 4 个中危漏洞）"

[packages-v2]
"curl" = "< 8.21.0"
"curl+32" = "< 8.21.0"
