security = true
must_match_all = false

[name]
default = "curl 8.17.0"

[caution]
default = "Fixes a path traversal vulnerability in wcurl(1) - CVE-2025-11563 (Severity: Moderate)"
zh_CN = "修复 wcurl(1) 中的一处路径遍历 (Path Traversal) 漏洞，漏洞编号 CVE-2025-11563（严重性：中）"

[packages-v2]
"curl" = "< 8.17.0"
