security = true
must_match_all = false

[name]
default = "curl 8.18.0"

[caution]
default = "Fixes 6 security vulnerabilities (including 5 of medium severity)"
zh_CN = "修复 6 处安全漏洞（含 5 个中危漏洞）"

[packages-v2]
"curl" = "< 8.18.0"
"curl+32" = "< 8.18.0"
