security = true
must_match_all = false

[name]
default = "Package Installation Wizard (deb-installer) 0.3.5"
zh_CN = "软件包安装向导 (deb-installer) 0.3.5"

[caution]
default = "Fixes a Missing Authorization vulnerability (Severity: High)"
zh_CN = "修复 1 个越权 (Missing Authorization) 漏洞（严重性：高）"

[packages-v2]
"deb-installer" = "< 0.3.5"
