security = true

[name]
default = "dnsmasq 2.93"

[caution]
default = "Fixes a Heap-Based Buffer Overflow vulnerability (CVE-2026-12725, Severity: Medium) and a Heap Out-of-Bounds Read vulnerability (CVE-2026-12969, Severity: Medium)"
zh_CN = "修复 1 个基于堆的缓冲区溢出漏洞（漏洞编号 CVE-2026-12725，严重性：中）和 1 个堆越界读取漏洞（漏洞编号 CVE-2026-12969，严重性：中）"

[packages-v2]
"dnsmasq" = "< 2.93"
