security = true
must_match_all = false

[name]
default = ".NET Runtime 10.0.7"
zh_CN = ".NET 运行时 10.0.7"

[caution]
default = "Fixes CVE-2026-40372 (Severity: Critical) and 4 high severity vulnerabilities"
zh_CN = "修复 CVE-2026-40372（严重性：严重）以及其他 4 个高危漏洞"

[packages-v2]
"dotnet-runtime-10.0" = "<10.0.7"
"aspnetcore-runtime-10.0" = "<10.0.7"
