security = true

[name]
default = "Dovecot 2.4.4"

[caution]
default = "Fixes 15 security vulnerabilities (including 1 of Critical, 7 of High, and 7 of Medium severity)"
zh_CN = "修复 15 个安全漏洞（含 1 个严重漏洞、7 个高危漏洞和 7 个中危漏洞）"

[packages-v2]
"dovecot" = "< 2.4.4"
