security = true

[name]
default = "Element Desktop 1.11.103 Security Update"
zh_CN = "Element Desktop 1.11.103 安全更新"
zh_TW = "Element Desktop 1.11.103 安全更新"

[caution]
default = "Fixes an encrypted event spoofing vulnerability - CVE-2025-48937"
zh_CN = "修复一处加密事件伪造漏洞 - CVE-2025-48937（严重性：高）"
zh_TW = "修復一處加密事件偽造漏洞 - CVE-2025-48937（嚴重性：高）"

[packages]
"element-desktop" = "1.11.103"
