security = true

[name]
default = "Emacs 30.2, Revision 6"
zh_CN = "Emacs 30.2，修订版本 6"

[caution]
default = "Fixes a OS Command Injection vulnerability"
zh_CN = "修复 1 个操作系统命令注入漏洞"

[packages-v2]
"emacs" = "< 30.2-6"
