security = true

[name]
default = "Erlang 29.0.2"

[caution]
default = "Fixes 9 security vulnerabilities (including 5 of High and 4 of Medium severity)"
zh_CN = "修复 9 个安全漏洞（含 5 个高危漏洞和 4 个中危漏洞）"

[packages-v2]
"erlang" = "< 29.0.2"
