security = true

[name]
default = "Erlang 29.0.5"

[caution]
default = "Fixes 8 security vulnerabilities (including 1 of Critical, 6 of High and 1 of Medium severity)"
zh_CN = "修复 8 个安全漏洞（含 1 个严重漏洞、6 个高危漏洞和 1 个中危漏洞）"

[packages-v2]
"erlang" = "< 29.0.5"
