security = true

[name]
default = "Exim 4.100.1"

[caution]
default = "Fixes 4 security vulnerabilities (including 2 of high severity, 1 of medium severity and 1 of low severity)"
zh_CN = "修复 4 个安全漏洞（含 2 个高危漏洞、1 个中危漏洞和 1 个低危漏洞）"

[packages-v2]
"exim" = "< 4.100.1"
