security = true

[name]
default = "Exim 4.99.4"

[caution]
default = "Fixes a Numeric Range Comparison Without Minimum Check vulnerability (CVE-2026-48840, Severity: Medium)"
zh_CN = "修复一处比较数值数值未检查最小值的漏洞（CVE-2026-48840，严重性：中）"

[packages-v2]
"exim" = "< 4.99.4"
