security = true

[name]
default = "Exim 4.98.2"
zh_CN = "Exim 4.98.2"

[caution]
default = "Fixes a remote SQL injection vulnerability - CVE-2025-54389 (Severity: High); Fixes a privilege escalation vulnerability - CVE-2025-54409 (Severity: High)"
zh_CN = "修复一处远程 SQL 注入漏洞，漏洞编号 CVE-2025-26794（严重性：高）；修复一处提权漏洞，漏洞编号 CVE-2025-30232（严重性：高）"

[packages]
"exim" = "4.98.2"
