security = true

[name]
default = "Exim 4.99.3"

[caution]
default = "Fixes 5 security vulnerabilities (including 3 of critical severity, 1 of high severity and 1 of medium severity)"
zh_CN = "修复 5 个安全漏洞（含 3 个严重漏洞、1 个高危漏洞和 1 个中危漏洞）"

[packages-v2]
"exim" = "< 4.99.3"
