security = true

[name]
default = "Exim 4.99.5"

[caution]
default = "Fixes 2 Local Privilege Escalation vulnerabilities (GCVE-25-2026-07-45-1 and GCVE-25-2026-07-45-3)"
zh_CN = "修复 2 个本地提权漏洞（GCVE-25-2026-07-45-1 和 GCVE-25-2026-07-45-3）"

[packages-v2]
"exim" = "< 4.99.5"
