security = true

[name]
default = "Exiv2 0.28.9"

[caution]
default = "Fixes an Uncaught Exception vulnerability (CVE-2026-27631, Severity: Low)"
zh_CN = "修复了 1 个未捕获异常漏洞（CVE-2026-27631，严重性：低）"

[packages-v2]
"exiv2" = "< 0.28.9"
