security = true

[name]
default = "Exiv2 0.28.7"

[caution]
default = "Fixes an Out-of-Bounds Read vulnerability (Severity: Medium, CVE-2025-54080) and a Denial-of-Service vulnerability (Severity: Medium, CVE-2025-55304)"
zh_CN = "修复一个越界读取漏洞（严重性：中，编号：CVE-2025-54080）和一个拒绝服务漏洞（严重性：中，编号：CVE-2025-55304）"

[packages-v2]
"exiv2" = "< 0.28.7"
