security = true

[name]
default = "Exiv2 2.8.7"

[caution]
default = "Fixes a out-of-bounds read vulnerability (Severity: Medium, CVE-2025-54080) and a denial-of-service vulnerability (Severity: Medium, CVE-2025-55304)"
zh_CN = "修复一个越界读取漏洞（严重性：中，编号：CVE-2025-54080）和一个拒绝服务漏洞（严重性：中，编号：CVE-2025-55304）"

[packages-v2]
"exiv2" = "< 2.8.7"
