security = true

[name]
default = "Exiv2 0.28.8"

[caution]
default = "Fixes 2 out-of-bounds read vulnerability (CVE-2026-25884, CVE-2026-27596, Severity: High), and an integer overflow vulnerability (CVE-2026-27631, Severity: Medium)"
zh_CN = "修复了两个越界读取漏洞（CVE-2026-25884、CVE-2026-27596，严重性：高），以及一个整数溢出漏洞（CVE-2026-27631，严重性：中等）"

[packages-v2]
"exiv2" = "< 0.28.8"
