security = true
must_match_all = false

[name]
default = "Expat 2.8.4"

[caution]
default = "Fixes 5 security vulnerabilities (including 2 of High Severity and 3 of Medium Severity)"
zh_CN = "修复 5 个安全漏洞（含 2 个高危漏洞和 3 个中危漏洞）"

[packages-v2]
"expat" = "< 2.8.4"
"expat+32" = "< 2.8.4"
