security = true
must_match_all = false

[name]
default = "Expat 2.8.2"

[caution]
default = "Fixes 13 security vulnerabilities (including 13 of Medium Severity)"
zh_CN = "修复 13 个安全漏洞（含 13 个中危漏洞）"

[packages-v2]
"expat" = "< 2.8.2"
"expat+32" = "< 2.8.2"
