security = true
must_match_all = false

[name]
default = "Expat 2.7.4"

[caution]
default = "Fixes a denial of service vulnerability (CVE-2025-66382, Severity: Medium), a null pointer dereference vulnerability (CVE-2026-24515, Severity: Critical), and a integer overflow vulnerability (CVE-2026-25210, Severity: Medium)"
zh_CN = "修复了一个拒绝服务漏洞（CVE-2025-66382，严重性：中等）、一个空指针解引用漏洞（CVE-2026-24515，严重性：严重），以及一个整数溢出漏洞（CVE-2026-25210，严重性：中等）"

[packages-v2]
"expat" = "< 2.7.4"
"expat+32" = "< 2.7.4"
