security = true
must_match_all = false

[name]
default = "Expat 2.9.0"

[caution]
default = "Fixes a Buffer Copy without Checking Size of Input vulnerability in XML_ParseBuffer (CVE-2026-77214, Severity: High) and an Integer Overflow vulnerability (CVE-2026-102633, Severity: High)"
zh_CN = "修复 1 个复制缓冲区时未检查输入大小漏洞（漏洞编号 CVE-2026-77214，严重性：高）和 1 个整数溢出漏洞（漏洞编号 CVE-2026-102633，严重性：高）"

[packages-v2]
"expat" = "< 2.9.0"
"expat+32" = "< 2.9.0"
