security = true
must_match_all = false

[name]
default = "Expat 2.8.0"

[caution]
default = "Fixes a hash flooding vulnerability (CVE-2026-41080, Severity: High)"
zh_CN = "修复一个哈希洪水漏洞（CVE-2026-41080，严重性：高）"

[packages-v2]
"expat" = "< 2.8.0"
"expat+32" = "< 2.8.0"
