security = true
must_match_all = true

[name]
default = "Expat 2.8.1"

[caution]
default = "Fixes an Inefficient Algorithmic Complexity vulnerability (CVE-2026-45186, Severity: High)"
zh_CN = "修复一个算法复杂度不足漏洞（CVE-2026-45186，严重性：高）"

[packages-v2]
"expat" = "< 2.8.1"
"expat+32" = "< 2.8.1"
