security = true
must_match_all = false

[name]
default = "Expat 2.7.5"

[caution]
default = "Fixes 2 null pointer dereference vulnerability (CVE-2026-32776, CVE-2026-32778, Severity: Medium) and an infinite loop vulnerability (CVE-2026-32777, Severity: Medium)"
zh_CN = "修复两个空指针解引用漏洞（CVE-2026-32776，CVE-2026-32778，严重性：中）和一个无限循环漏洞（CVE-2026-32777，严重性：中）"

[packages-v2]
"expat" = "< 2.7.5"
"expat+32" = "< 2.7.5"
