security = true

[name]
default = "Expat XML Parser 2.7.2"
zh_CN = "Expat XML 解析器 2.7.2"

[caution]
default = "Fixes a memory-amplification DoS vulnerability - CVE-2025-59375 (Severity: High)"
zh_CN = "修复一处内存放大型拒绝服务 (DoS) 漏洞，漏洞编号 CVE-2025-59375（严重性：高）"

[packages]
"expat" = "2.7.2"
"expat+32" = "2.7.2"
