security = true
must_match_all = false

[name]
default = "FFmpeg 8.1.2"

[caution]
default = "Fixes a Remote Code Escalation vulnerability (\"PixelSmash\") - CVE-2026-8461 (severity: High)"
zh_CN = "修复一个远程代码执行漏洞 (\"PixelSmash\") ，漏洞编号 CVE-2026-8461（严重性：高）"

[packages-v2]
"ffmpeg" = "< 8.1.2"
"ffmpeg-static-libs-for-sunshine" = "< 8.1.2"
"ffmpeg+32" = "< 8.1.2"
