security = true

[name]
default = "Firefox ESR 140.11.0esr"

[caution]
default = "Fixes 20 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2026-48 (6 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2026-48 号安全公告中披露的 20 个安全漏洞（含 6 个高危漏洞）"

[packages-v2]
firefox-esr = "< 140.11.0esr"
