security = true

[name]
default = "Firefox 143.0"

[caution]
default = "Fixes 11 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-73 (3 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-73 号安全公告中披露的 11 个安全漏洞（含 3 个高危漏洞）"

[packages]
firefox = "143.0"
