security = true

[name]
default = "Firefox 147.0"

[caution]
default = "Fixes 16 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2026-01 (6 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2026-01 号安全公告中披露的 16 个安全漏洞（含 6 个高危漏洞）"

[packages-v2]
firefox = "< 147.0"
