security = true

[name]
default = "Firefox 137.0.2"

[caution]
default = "Fixes 1 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-25 (1 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-25 号安全公告中披露的 1 个安全漏洞（含 1 个高危漏洞）"

[packages]
firefox = "137.0.2"
