security = true

[name]
default = "Firefox 144.0"

[caution]
default = "Fixes 14 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-81 (7 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-81 号安全公告中披露的 14 个安全漏洞（含 7 个高危漏洞）"

[packages-v2]
firefox = "< 144.0"
