security = true

[name]
default = "Firefox 149.0"

[caution]
default = "Fixes 46 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2026-20 (19 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2026-20 号安全公告中披露的 46 个安全漏洞（含 19 个高危漏洞）"

[packages-v2]
firefox = "< 149.0"
