security = true

[name]
default = "Firefox 145.0"

[caution]
default = "Fixes 16 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-87 (9 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-87 号安全公告中披露的 16 个安全漏洞（含 9 个高危漏洞）"

[packages-v2]
firefox = "< 145.0"
