security = false
must_match_all = false

[name]
default = "Device Driver Firmware and Microcode Update (February 6, 2026)"
zh_CN = "设备驱动固件及微码更新（2026 年 2 月 6 日）"

[caution]
default = "With enhancements for various audio, graphics, networking, and SoC devices and platforms, with a fix for unresponsive desktop or freezes on platforms based on the AMD Pheonix APUs, as well as added support for audio, graphics, NPU, and networking devices found on Intel Panther Lake platforms"
zh_CN = "包含对数款音频、图形和网络设备，以及 SoC 平台的支持增强，修复 AMD Pheonix APU 硬件平台偶发桌面无响应或锁死的问题，并新增 Intel Panther Lake 平台音频、图形、NPU 及网络设备的支持"

[packages-v2]
"firmware-nonfree" = "< 20260110+debian20251125+1"
"sof-firmware" = "< 2025.12.2"
