security = true

[name]
default = "Flask 3.1.3"

[caution]
default = "Fixes an Use of Cache Containing Sensitive Information vulnerability (CVE-2026-27205, Severity: Low)"
zh_CN = "修复一个通过缓存导致的信息暴露漏洞（CVE-2026-27205，严重性：低）"

[packages-v2]
"flask" = "< 3.1.3"
