security = true

[name]
default = "flatpak-builder 1.4.8"

[caution]
default = "Fixes a Path Traversal vulnerability (CVE-2026-39977, Severity: Medium)"
zh_CN = "修复一个路径穿越漏洞（漏洞编号 CVE-2026-39977，严重性：中）"

[packages-v2]
"flatpak-builder" = "< 1.4.8"
