security = true

[name]
default = "Flatpak 1.18.4"

[caution]
default = "Fixes 6 security vulnerabilities (including 2 of High, 1 of Medium, and 3 of Low severity)"
zh_CN = "修复 6 个安全漏洞（含 2 个高危漏洞、1 个中危漏洞和 3 个低危漏洞）"
zh_TW = "修復 6 個安全漏洞（含 2 個高危漏洞、1 個中危漏洞和 3 個低危漏洞）"

[packages-v2]
"flatpak" = "< 1.17.5"
