security = true

[name]
default = "Flatpak 1.17.5"

[caution]
default = "Fixes 4 security vulnerabilities (including 1 of Critical and 1 of High severity)"
zh_CN = "修复 4 个安全漏洞（含 1 个严重漏洞和 1 个高危漏洞）"

[packages-v2]
"flatpak" = "< 1.17.5"
