security = true

[name]
default = "Fractal 11.2 Security Update"
zh_CN = "Fractal 11.2 安全更新"
zh_TW = "Fractal 11.2 安全更新"

[caution]
default = "Fixes an encrypted event spoofing vulnerability - CVE-2025-48937"
zh_CN = "修复一处加密事件伪造漏洞 - CVE-2025-48937（严重性：高）"
zh_TW = "修復一處加密事件偽造漏洞 - CVE-2025-48937（嚴重性：高）"

[packages]
"fractal" = "11.2"
