security = true

[name]
default = "FreeRDP 3.31.0"

[caution]
default = "Fixes 22 security vulnerabilities partially publicly disclosed by FreeRDP Security Team (including 1 of critical severity, 7 of high severity)"
zh_CN = "修复 FreeRDP 安全团队部分披露的 22 个安全漏洞（含 1 个严重漏洞，7 个高危漏洞）"

[packages-v2]
freerdp = "< 2:3.31.0"
