security = true

[name]
default = "FreeRDP 3.23.0"

[caution]
default = "Fixes 44 security vulnerabilities disclosed by FreeRDP Security Team since January 24, 2026 (2 of high severity)"
zh_CN = "修复 FreeRDP 安全团队自 2026 年 1 月 24 日以来披露的 44 个安全漏洞（含 2 个高危漏洞）"

[packages-v2]
freerdp = "< 2:3.23.0"
