security = true

[name]
default = "gdk-pixbuf 2.44.4"

[caution]
default = "Fixes a heap-based buffer overflow vulnerability - CVE-2025-7345 (Severity: High)"
zh_CN = "修复一处堆缓冲区溢出漏洞 CVE-2025-7345（严重性：高）"

[packages-v2]
"gdk-pixbuf" = "< 2.44.4"
