security = true
must_match_all = false

[name]
default = "Giflib 6.1.3"

[caution]
default = "Fixes 2 Out-of-Bounds Write vulnerability (CVE-2024-45993/CVE-2026-26740, Severity: Medium/High), a Double Free vulnerability (CVE-2026-23868, Severity: High)"
zh_CN = "修复了 2 个越界写入漏洞（CVE-2024-45993、CVE-2026-26740，严重性：中、高）和 1 个双重释放漏洞（CVE-2026-23868，严重性：高）"

[packages-v2]
"giflib" = "< 6.1.3"
"giflib+32" = "< 6.1.3"
