security = true
must_match_all = false

[name]
default = "Git 2.50.1"
zh_CN = "Git 2.50.1"

[caution]
default = "Fixes 5 high severity vulnerabilities including 2 remote code execution vulnerabilities - CVE-2025-48385 and CVE-2025-48386"
zh_CN = "修复五处高危漏洞，包含两处远程代码执行漏洞 (CVE-2025-48385, CVE-2025-48386)"

[packages]
git = "2.50.1"
gitk = "2.50.1"
git-gui = "2.50.1"
