security = true

[name]
default = "Git LFS 3.6.1 Security Update"
zh_CN = "Git LFS 3.6.1 安全更新"

[caution]
default = "Fixes a credential leak vulnerability - CVE-2024-53263 (Severity: High)"
zh_CN = "修复一处身份泄漏漏洞，漏洞编号 CVE-2024-53263（严重性：高）"

[packages]
git-lfs = "3.6.1"
