security = true
must_match_all = false

[name]
default = "Gitea and Forgejo security update (July, 2026)"
zh_CN = "Gitea 与 Forgejo 安全更新（2026 年 7 月）"

[caution]
default = "Fixes a path traversal vulnerability (CVE-2026-59774, Severity: Critical) and a code injection vulnerability (CVE-2026-60004, Severity: Critical)"
zh_CN = "修复 1 个路径遍历漏洞（CVE-2026-59774，严重性：严重）与 1 个代码注入漏洞（CVE-2026-60004，严重性：严重）"

[packages-v2]
"gitea" = "< 1.27.1"
"forgejo" = "< 16.0.2"
