security = true

[name]
default = "GLib 2.88.2"

[caution]
default = "Fixes 7 security vulnerabilities (including 1 of critical severity and 6 of high severity)"
zh_CN = "修复 7 处安全漏洞（含 1 个严重漏洞和 6 个高危漏洞）"

[packages-v2]
"glib" = "< 2.88.2"
"glib+32" = "< 2.88.2"
