security = true

[name]
default = "GLib 2.86.3"

[caution]
default = "Fixes a heap-based buffer overflow in the URI string escaping, which may cause remote code execution or a denial of service (Severity: High)"
zh_CN = "修复 URI 字符串转义时的一处堆缓冲区溢出漏洞，该漏洞可能导致远程代码执行或拒绝服务（严重性：高）"

[packages-v2]
"glib" = "< 2.86.3"
