security = true

[name]
default = "GnuPG 2.5.17"

[caution]
default = "Fixes a remote code execution vulnerability - CVE-2026-24881, CVE-2026-24882, and CVE-2026-24883 (Severity: Critical)"
zh_CN = "修复了一处远程代码执行漏洞，漏洞编号 CVE-2026-24881、CVE-2026-24882 及 CVE-2026-24883（严重性：严重）"

[packages-v2]
"gnupg" = "< 2.5.17"
