security = true

[name]
default = "GnuPG 2.5.16"

[caution]
default = "Fixes a logic vulnerability (CVE-2025-68972, Severity: Medium) and a out-of-bounds write vulnerability (CVE-2025-68973, Severity: High)"
zh_CN = "修复了一处逻辑漏洞（CVE-2025-68972，严重性：中等）和一处越界写入漏洞（CVE-2025-68973，严重性：高）"

[packages-v2]
"gnupg" = "< 2.5.16"
