security = true
must_match_all = false

[name]
default = "gnutls 3.8.13"

[caution]
default = "Fixes 12 security vulnerabilities (including 5 of high severity and 5 of medium severity)"
zh_CN = "修复 12 处安全漏洞（含 5 个高危漏洞及 5 个中危漏洞）"

[packages-v2]
"gnutls" = "< 3.8.13"
"gnutls+32" = "< 3.8.13"
