security = true
must_match_all = false

[name]
default = "GnuTLS 3.8.12"

[caution]
default = "Fixes a denial of service vulnerability (CVE-2025-14831, Severity: Medium) and a null pointer dereference vulnerability (CVE-2026-1584, Severity: High)"
zh_CN = "修复了一个拒绝服务漏洞（CVE-2025-14831，严重性：中等）和一个空指针解引用漏洞（CVE-2026-1584，严重性：高）"

[packages-v2]
"gnutls" = "< 3.8.12"
"gnutls+32" = "< 3.8.12"
