security = true

[name]
default = "GnuTLS 3.8.10"

[caution]
default = "Fixes 3 security vulnerabilities disclosed in GnuTLS Security Advisories on July 8, 2025 (Severity: Moderate)"
zh_CN = "修复 GnuTLS 在 2025 年 7 月 8 日的安全公告中披露的 3 个安全漏洞（严重性：中等）"

[packages-v2]
"gnutls" = "< 3.8.10"
