security = true

[name]
default = "Go 1.26.5"

[caution]
default = "Fixes a root escape vulnerability (CVE-2026-39822, Severity: High) and an Encrypted Client Hello privacy leak vulnerability (CVE-2026-42505, Severity: Medium)"
zh_CN = "修复了一个根目录逃逸漏洞（CVE-2026-39822，严重性：高）和一个 Encrypted Client Hello 隐私泄露漏洞（CVE-2026-42505，严重性：中等）"

[packages-v2]
go = "< 1.26.5+tools0.45.0"
