security = true

[name]
default = "Go 1.25.3"

[caution]
default = "Fixes 10 security vulnerabilities (including 1 of high severity and 9 of medium severity)"
zh_CN = "修复十处安全漏洞（含 1 个高危漏洞, 9 个中危漏洞）"

[packages-v2]
go = "< 1.25.3+tools0.34.0+net0.41.0"
