security = true

[name]
default = "Go 1.25.5"

[caution]
default = "Fixes 2 security vulnerabilities in the crypto/x509 package"
zh_CN = "修复 crypto/x509 软件包中的 2 个安全漏洞"

[packages-v2]
go = "< 1.25.5+tools0.34.0+net0.41.0"
