security = true

[name]
default = "Go 1.26.4"

[caution]
default = "Fixes 3 security vulnerabilities (including 1 of high severity and 2 of medium severity)"
zh_CN = "修复 3 个安全漏洞（含 1 个高危漏洞, 2 个中危漏洞）"

[packages-v2]
go = "< 1.26.4+tools0.42.0"
