security = true

[name]
default = "Go 1.27.0"

[caution]
default = "Fixes 10 security vulnerabilities (including 8 of high severity and 2 of medium severity)"
zh_CN = "修复 10 个安全漏洞（含 8 个高危漏洞, 2 个中危漏洞）"

[packages-v2]
go = "< 1.27.0+tools0.49.0"
