security = true

[name]
default = "gRPC 1.80.0"

[caution]
default = "Fixes an authorization bypass vulnerabilities (CVE-2026-33186, Severity: Critical)"
zh_CN = "修复一个授权绕过漏洞（漏洞编号CVE-2026-33186，严重性：严重）"

[packages-v2]
"grpc" = "< 1.80.0"
