security = true

[name]
default = "GStreamer 1.28.7"

[caution]
default = "Fixes 69 security vulnerabilities (from GStreamer-SA-2026-0013 to GStreamer-SA-2026-0082)"
zh_CN = "修复 69 个安全漏洞（自 GStreamer-SA-2026-0013 至 GStreamer-SA-2026-0082）"

[packages-v2]
"gstreamer" = "< 1.28.7"
