security = true

[name]
default = "GNU zip 1.14, Revision 1"
zh_CN = "GNU zip 1.14，修订版本 1"

[caution]
default = "Fixes a Buffer Over-read vulnerability (CVE-2026-41992, severity: High)"
zh_CN = "修复 1 个缓冲区越界读取漏洞（CVE-2026-41992，严重性：高）"

[packages-v2]
"gzip" = "< 1.14-1"
