security = true

[name]
default = "Gzip 1.15"

[caution]
default = "Fixes an Insecure Temporary File vulnerability (CVE-2026-41991, Severity: Low) and a Buffer Over-read vulnerability (CVE-2026-41992, Severity: Medium)"
zh_CN = "修复 1 个不安全临时文件漏洞（CVE-2026-41991，严重性：低）和 1 个缓冲区越界读取漏洞（CVE-2026-41992，严重性：中）"

[packages-v2]
"gzip" = "< 1:1.15"
