security = true

[name]
default = "Halloy 2026.5"

[caution]
default = "Fixes a path traversal vulnerabilities (CVE-2026-32733, Severity: High) and a credentials leak vulnerability (CVE-2026-32810, Severity: Medium)"
zh_CN = "修复一个路径穿越漏洞（漏洞编号 CVE-2026-32733，严重性：高）和一个凭据泄漏漏洞（漏洞编号 CVE-2026-32810，严重性：中等）"

[packages-v2]
"halloy" = "< 2026.5"
