security = true

[name]
default = "haveged 1.9.21"

[caution]
default = "Fixes a Local Privilege Escalation vulnerability (CVE-2026-41054, Severity: Moderate)"
zh_CN = "修复一个本地提权漏洞（CVE-2026-41054，严重性：中）"

[packages-v2]
"haveged" = "< 1.9.21"
