security = true

[name]
default = "Helm 4.1.4"

[caution]
default = "Fixes a path traversal vulnerability (CVE-2026-35204, Severity: High), a plugin verification bypass vulnerability (CVE-2026-35205, Severity: High), and a file override vulnerability (CVE-2026-35206, Severity: Medium)"
zh_CN = "修复了一个路径穿越漏洞（CVE-2026-35204，严重性：高）、一个插件验证绕过漏洞（CVE-2026-35205，严重性：高），以及一个文件覆盖漏洞（CVE-2026-35206，严重性：中等）"

[packages-v2]
"helm" = "< 4.1.4"
