security = true

[name]
default = "Helm 4.1.3"

[caution]
default = "Fixes 5 security vulnerabilities (including 4 of high severity and 1 of medium severity)"
zh_CN = "修复 5 处安全漏洞（含 4 个高危漏洞和 1 个中危漏洞）"

[packages-v2]
"helm" = "< 4.1.3"
