security = true

[name]
default = "hostapd 2.12"

[caution]
default = "Fixes an Off-by-one Error vulnerability (CVE-2026-58374, Severity: High) and a Premature Release of Resource During Expected Lifetime vulnerability (CVE-2026-58375, Severity: Low)"
zh_CN = "修复 1 个差一错误漏洞（CVE-2026-58374，严重性：高）和 1 个在生命周期内过早释放资源漏洞（CVE-2026-58375，严重性：低）"

[packages-v2]
"hostapd" = "< 2.12"
