security = true

[name]
default = "Host Access Point Daemon (hostapd) 2.11, Revision 1"
zh_CN = "主机无线接入点守护程序 (hostapd) 2.11，修订 1"

[caution]
default = "Fixes an Out-of-bounds Write (or Pre-authentication Denial-of-Service) vulnerability"
zh_CN = "修复一个越界写入 (Out-of-bounds Write)，或预鉴权拒绝服务 (Pre-authentication Denial-of-Service) 漏洞"

[packages-v2]
"hostapd" = "< 2.11-1"
