security = true

[name]
default = "Apache HTTP Server (httpd) 2.4.66"
zh_CN = "Apache HTTP 服务器 (httpd) 2.4.66"

[caution]
default = "Fixes 13 security vulnerabilities since Apache HTTP Server 2.4.63 (1 of critical severity, 10 of high severity)"
zh_CN = "修复 Apache HTTP Sever 2.4.63 起披露的 13 个安全漏洞（含 1 个严重漏洞和 10 个高危漏洞）"

[packages-v2]
"httpd" = "< 2.4.66"
