security = true

[name]
default = "Apache HTTP Server (httpd) 2.4.67-2"
zh_CN = "Apache HTTP 服务器 (httpd) 2.4.67-2"

[caution]
default = "Fixes a memory-amplification DoS vulnerability (\"HTTP/2 Bomb\") - CVE-2026-49975"
zh_CN = "修复 1 个内存放大型拒绝服务 (DoS) 漏洞 (\"HTTP/2 Bomb\")，漏洞编号 CVE-2026-49975"

[packages-v2]
"httpd" = "< 2.4.67-2"
