security = true

[name]
default = "Apache HTTP Server (httpd) 2.4.68"
zh_CN = "Apache HTTP 服务器 (httpd) 2.4.68"

[caution]
default = "Fixes 13 security vulnerabilities"
zh_CN = "修复 13 个安全漏洞"

[packages-v2]
"httpd" = "< 2.4.68"
