security = true

[name]
default = "Hugo 0.160.1"

[caution]
default = "Fixes a text escape vulnerability (CVE-2026-35166, Severity: Medium)"
zh_CN = "修复一个文本转义漏洞（CVE-2026-35166，严重性：中）"

[packages-v2]
"hugo" = "< 0.160.1"
