security = true

[name]
default = "ImageMagick 7.1.2+30"

[caution]
default = "Fixes 6 security vulnerabilities (including 6 of Low Severity)"
zh_CN = "修复 6 个安全漏洞（含 6 个低危漏洞）"

[packages-v2]
"imagemagick" = "< 7.1.2+30"
