security = true

[name]
default = "ImageMagick 6.9.13-37"

[caution]
default = "Fixes 10 security vulnerabilities since ImageMagick 6.9.13-16 (4 of high severity)"
zh_CN = "修复自 ImageMagick 6.9.13-16 以来的 10 个安全漏洞（含 4 个高危漏洞）"

[packages-v2]
"imagemagick" = "< 6.9.13+37"
