security = true

[name]
default = "Incus 6.23.0"

[caution]
default = "Fixes 6 security vulnerabilities (including 3 of critical severity and 1 of high severity)"
zh_CN = "修复 6 个安全漏洞（含 3 个严重漏洞及 1 个高危漏洞）"

[packages-v2]
"incus" = "< 6.23.0"
