security = true

[name]
default = "Incus 7.4.0"

[caution]
default = "Fixes a Path Traversal vulnerability (Severity: Moderate, CVE-2026-81500) and an Access Control vulnerability (Severity: Moderate, CVE-2026-81501)"
zh_CN = "修复 1 个路径遍历漏洞（严重性：中，CVE-2026-81500）和 1 个访问控制漏洞（严重性：中，CVE-2026-81501）"

[packages-v2]
"incus" = "< 7.4.0"
