security = true

[name]
default = "Incus 7.2.0"

[caution]
default = "Fixes 8 security vulnerabilities (including 6 of critical severity and 2 of high severity)"
zh_CN = "修复 8 处安全漏洞（含 6 个严重漏洞和 2 个高危漏洞）"

[packages-v2]
"incus" = "< 7.2.0"
