security = true

[name]
default = "GNU InetUtils 2.7"

[caution]
default = "Fixes a Remote Authentication Bypass vulnerability in telnetd (Severity: Critical)"
zh_CN = "修复一处远程鉴权绕过 (Remote Authentication Bypass) 漏洞（严重性：严重）"

[packages-v2]
"inetutils" = "< 2.7"
