security = true

[name]
default = "GNU InetUtils 2.8, Revision 1"
zh_CN = "GNU InetUtils 2.8，修订版本 1"

[caution]
default = "Fixes a Buffer Overflow vulnerability"
zh_CN = "修复 1 个缓冲区溢出漏洞"

[packages-v2]
"inetutils" = "< 2.8-1"
