security = true

[name]
default = "Intel Processor Microcode Package for Linux, version 20250512"
zh_CN = "适用于 Linux 的 Intel 处理器微码包，版本 20250512"

[caution]
default = "Fixes self-training Spectre-v2 (Exposure of Sensitive Information) vulnerability codenamed \"Training Solo\""
zh_CN = "修复代号为 \"Training Solo\" 的自训练 Spectre-v2（敏感信息泄漏）漏洞"

[packages]
intel-ucode = "20250512"
