security = true

[name]
default = "kdiskmark 3.2.0"

[caution]
default = "Fixes a D-Bus authentication vulnerability - CVE-2022-40673 (Severity: High)"
zh_CN = "修复一处 D-Bus 鉴权漏洞，漏洞编号 CVE-2022-40673（严重性：高）"

[packages-v2]
"kdiskmark" = "< 3.2.0"
