security = true

[name]
default = "Krita 5.2.13"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability - CVE-2025-59820 (Severity: Medium)"
zh_CN = "修复一处堆缓冲区溢出 (Heap-based Buffer Overflow) 漏洞，漏洞编号 CVE-2025-59820（严重性：中）"

[packages-v2]
"krita" = "< 5.2.13"
