security = true

[name]
default = "ldns 1.9.2"

[caution]
default = "Fixes an Origin Validation Error vulnerability (CVE-2026-10846, severity: High)"
zh_CN = "修复一个源验证错误漏洞（漏洞编号 CVE-2026-10846，严重性：高）"

[packages-v2]
"ldns" = "< 1.9.2"
