security = true

[name]
default = "libarchive 3.7.8"

[caution]
default = "Fixes multiple security vulnerabilities (3 of medium severity)"
zh_CN = "修复三个安全漏洞（含 3 个中危漏洞）"

[packages]
libarchive = "1:3.7.8"
