security = true

[name]
default = "libblockdev 3.3.1"

[caution]
default = "Fixes a local privilege escalation vulnerability - CVE-2025-6019 (Severity: Critical)"
zh_CN = "修复一处编号为 CVE-22025-6019 本地提权漏洞（严重性：严重）"

[packages]
"libblockdev" = "3.3.1"
