security = true
must_match_all = false

[name]
default = "libcaca 0.99.beta20"

[caution]
default = "Fixes 2 high severity and 1 medium severity security vulnerabilities"
zh_CN = "修复 2 个高危和 1 个中危安全漏洞"

[packages-v2]
"libcaca" = "< 0.99.beta20"
"libcaca+32" = "< 0.99.beta20"
