security = true
must_match_all = false

[name]
default = "libcap 2.78"

[caution]
default = "Fixes a TOCTOU (Time-Of-Check to Time-of-Use) race condition vulnerability - CVE-2026-4878 (severity: High)"
zh_CN = "修复一处 TOCTOU（检查到使用时间）竞态条件漏洞，漏洞编号 CVE-2026-4878（严重性：高）"

[packages-v2]
"libcap" = "< 2.78"
"libcap+32" = "< 2.78"
