security = true

[name]
default = "libde265 1.0.16"

[caution]
default = "Fixes 2 heap buffer overflow vulnerabilities - CVE-2024-38949, CVE-2024-38950  (Severity: Medium)"
zh_CN = "修复 2 处堆缓冲区溢出漏洞，漏洞编号 CVE-2024-38949 和 CVE-2024-38950（严重性：中）"

[packages-v2]
"libde265" = "< 1.0.16"
