security = true

[name]
default = "libde265 1.0.18"

[caution]
default = "Fixes a buffer overflow vulnerability (CVE-2025-61147, Severity: Medium), a NULL pointer dereference vulnerability (CVE-2026-33164, Severity: High), and an out-of-bounds write vulnerability (CVE-2026-33165, Severity: Medium)"
zh_CN = "修复一个缓冲区溢出漏洞（CVE-2025-61147，严重性：中）、一个空指针解引用漏洞（CVE-2026-33164，严重性：高）和一个越界写入漏洞（CVE-2026-33165，严重性：中）"

[packages-v2]
"libde265" = "< 1.0.18"
