security = true
must_match_all = false

[name]
default = "libexif 0.6.26"

[caution]
default = "Fixes 2 integer underflow vulnerability (CVE-2026-32775, CVE-2026-40386, Severity: High) and an integer overflow vulnerability (CVE-2026-40385, Severity: High)"
zh_CN = "修复两个整数下溢漏洞（CVE-2026-32775、CVE-2026-40386，严重性：高）和一个整数溢出漏洞（CVE-2026-40385，严重性：高）"

[packages-v2]
"libexif" = "< 0.6.26"
"libexif+32" = "< 0.6.26"
