security = true

[name]
default = "Libevent 2.1.13"

[caution]
default = "Fixes 10 security vulnerabilities (including 6 of High and 4 of Moderate severity)"
zh_CN = "修复 10 个安全漏洞（含 6 个高危漏洞和 4 个中危漏洞）"

[packages-v2]
"libevent" = "< 2.1.13"
