security = true

[name]
default = "libebml 1.4.6"

[caution]
default = "Fixes an Out-of-bounds Write vulnerability (CVE-2021-3405, Severity: Medium) and an Integer Overflow vulnerability (CVE-2023-52339, Severity: Medium)"
zh_CN = "修复 1 个越界写漏洞（漏洞编号 CVE-2021-3405，严重性：中）和 1 个整数溢出漏洞（漏洞编号 CVE-2023-52339，严重性：中）"

[packages-v2]
"libebml" = "< 1.4.6"
