security = true

[name]
default = "libgxps 0.3.2"

[caution]
default = "Fixes a null pointer vulnerability (Severity: High), a heap buffer overflow vulnerability (Severity: Medium) and a stack buffer overflow vulnerability (Severity: Medium)"
zh_CN = "修复一个空指针漏洞（严重性：高）、一个堆缓冲区溢出漏洞（严重性：中）和一个栈缓冲区溢出漏洞（严重性：中）"

[packages-v2]
"libgxps" = "< 0.3.2"
