security = true

[name]
default = "libgig 4.5.2"

[caution]
default = "Fixes a heap buffer overflow vulnerability - CVE-2021-32294 (Severity: High)"
zh_CN = "修复一个堆缓冲区溢出漏洞，漏洞编号 CVE-2021-32294（严重性：高）"

[packages-v2]
"libgig" = "< 4.5.2"
