security = true
must_match_all = false

[name]
default = "Libgcrypt 1.12.2"

[caution]
default = "Fixes an Out-of-bounds Write vulnerability (CVE-2026-41989, Severity: Medium)"
zh_CN = "修复一个越界写入漏洞（CVE-2026-41989，严重性：中）"

[packages-v2]
"libgcrypt" = "< 1.12.2"
"libgcrypt+32" = "< 1.12.2"
