security = true

[name]
default = "libheif 1.22.0"

[caution]
default = "Fixes 2 Out-of-Bounds Read vulnerabilities (CVE-2026-32738, CVE-2026-32740, Severity: Medium, High) and a Loop with Unreachable Exit Condition vulnerability (CVE-2026-32739, Severity: Medium)"
zh_CN = "修复两个越界读取漏洞（漏洞编号 CVE-2026-32738、CVE-2026-32740，严重性：中、高）和一个无限循环漏洞（漏洞编号 CVE-2026-32739，严重性：中）"

[packages-v2]
"libheif" = "< 1.22.0"
