security = true

[name]
default = "libheif 1.21.2"

[caution]
default = "Fixes a heap buffer over vulnerability - CVE-2025-68431 (Severity: High)"
zh_CN = "修复一个堆缓冲区溢出漏洞，漏洞编号 CVE-2025-68431（严重性：高）"

[packages-v2]
"libheif" = "< 1.21.2"
