security = true

[name]
default = "libinput 1.31.3"

[caution]
default = "Fixes a Improper Neutralization of CRLF Sequences (CRLF Injection) vulnerability (CVE-2026-50292, severity: High)"
zh_CN = "修复一个 CRLF 序列处理不当（CRLF 注入）漏洞（漏洞编号 CVE-2026-50292，严重性：高）"

[packages-v2]
libinput = "< 1.31.3"
