security = true

[name]
default = "libjxl 0.11.2"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability (CVE-2025-70103, Severity: High), an use of uninitialized resource vulnerability (CVE-2025-12474, Severity: Medium) and an allocation of resources without limits or throttling vulnerability (CVE-2026-1837, Severity: High)"
zh_CN = "修复一个基于堆的缓冲区溢出漏洞（CVE-2025-70103，严重性：高）、一个使用未初始化资源的漏洞（CVE-2025-12474，严重性：中）和一个无限资源分配漏洞（CVE-2026-1837，严重性：高）"

[packages-v2]
"libjxl" = "< 0.11.2"
