security = true

[name]
default = "liblouis 3.36.0"

[caution]
default = "Fixes a buffer overflow vulnerability - CVE-2022-26981 (Severity: High)"
zh_CN = "修复一个缓冲区溢出漏洞，漏洞编号 CVE-2022-26981（严重性：高）"

[packages-v2]
"liblouis" = "< 3.36.0"
