security = true

[name]
default = "liblol 0.1.11"

[caution]
default = "Updates glibc to 2.44, fixes 14 security vulnerabilites disclosed in glibc security advisories GLIBC-SA-2026-0011 through GLIBC-SA-2026-0024 (including 2 of High severity)"
zh_CN = "更新 glibc 到 2.44，修复 glibc 安全公告 GLIBC-SA-2026-0011 至 GLIBC-SA-2026-0024 中披露的 14 个安全漏洞（含 2 个高危漏洞）"

[packages-v2]
"liblol" = "< 0.1.11"
