security = true

[name]
default = "libmicrohttpd 1.0.2"

[caution]
default = "Fixes 2 null pointer vulnerabilities - CVE-2025-59777, CVE-2025-62689 (Severity: High)"
zh_CN = "修复 2 个空指针漏洞，漏洞编号 CVE-2025-59777 和 CVE-2025-62689（严重性：高）"

[packages-v2]
"libmicrohttpd" = "< 1.0.2"
