security = true
must_match_all = false

[name]
default = "libpng 1.6.59"

[caution]
default = "Fixes a Use-After-Free vulnerability (CVE-2026-46675, Severity: Medium)"
zh_CN = "修复 1 个释放后使用漏洞（CVE-2026-46675，严重性：中）"

[packages-v2]
"libpng" = "< 1.6.59"
"libpng+32" = "< 2:1.6.59"
