security = true
must_match_all = false

[name]
default = "libpng 1.6.57"

[caution]
default = "Fixes a Use-After-Free vulnerability - CVE-2026-34757 (Severity: Medium)"
zh_CN = "修复一个释放后使用 (Use-After-Free) 漏洞（CVE-2026-34757，严重性：中）"

[packages-v2]
"libpng" = "< 1.6.57"
"libpng+32" = "< 2:1.6.57"
