security = true

[name]
default = "libpcap 1.10.6"

[caution]
default = "Fixes a double free vulnerability (CVE-2023-7256, Severity: Medium) and a null pointer dereference vulnerability (CVE-2024-8006, Severity: Medium)"
zh_CN = "修复一个双重释放漏洞（CVE-2023-7256，严重性：中）和一个内存泄漏漏洞（CVE-2024-8006，严重性：中）"

[packages-v2]
"libpcap" = "< 1.10.6"
