security = true

[name]
default = "libpcap 1.10.7"

[caution]
default = "Fixes 7 security vulnerabilities (including 1 of high severity and 6 of medium severity)"
zh_CN = "修复 7 个安全漏洞（含 1 个高危漏洞及 6 个中危漏洞）"

[packages-v2]
"libpcap" = "< 1.10.7"
