security = true
must_match_all = false

[name]
default = "libpng 1.6.56"

[caution]
default = "Fixes a heap-based buffer overflow vulnerability (CVE-2026-3713, Severity: Medium)"
zh_CN = "修复一个基于堆的缓冲区溢出漏洞（CVE-2026-3713，严重性：中）"

[packages-v2]
"libpng" = "1.6.56"
"libpng+32" = "1.6.56"
