security = true
must_match_all = false

[name]
default = "libpng 1.6.55"

[caution]
default = "Fixes 9 security vulnerabilities (including 5 of high severity and 4 of medium severity)"
zh_CN = "修复 9 处安全漏洞（含 5 个高危漏洞及 4 个中危漏洞）"

[packages-v2]
"libpng" = "< 1.6.55"
"libpng+32" = "< 1.6.55"
