security = true

[name]
default = "LibRaw 0.22.2"

[caution]
default = "Fixes 4 security vulnerabilities (4 of critical severity)"
zh_CN = "修复 4 处安全漏洞（含 4 个严重漏洞）"

[packages-v2]
"libraw" = "< 0.22.2"
