security = true

[name]
default = "LibreOffice 26.2.4.1"

[caution]
default = "Fixes an Out-of-Bounds Write vulnerability (CVE-2026-4430, Severity: High)"
zh_CN = "修复一个越界写入漏洞（CVE-2026-4430，严重性：高）"

[packages-v2]
"LibreOffice" = "< 26.2.4.1"
