security = true

[name]
default = "LibRaw 0.22.1"

[caution]
default = "Fixes 10 security vulnerabilities (including 4 of critical severity, 5 of high severity and 4 of medium severity)"
zh_CN = "修复 10 处安全漏洞（含 4 个严重漏洞、2 个高危漏洞及 4 个中危漏洞）"

[packages-v2]
"libraw" = "< 0.22.1"
