security = true
must_match_all = false

[name]
default = "libssh2 1.11.1, Revision 1"
zh_CN = "libssh2 1.11.1，修订 1"

[caution]
default = "Fixes 4 security vulnerabilities (1 of Critical severity, 3 of High severity)"
zh_CN = "修复 4 个安全漏洞（含 1 个严重漏洞，3 个高危漏洞）"

[packages-v2]
"libssh2" = "< 1.11.1-1"
"libssh2+32" = "< 1.11.1-1"
