security = true

[name]
default = "libsixel 1.8.7+r1"

[caution]
default = "Fixes 7 security vulnerabilities (including 5 of high severity)"
zh_CN = "修复 7 处安全漏洞（含 5 个高危漏洞）"

[packages-v2]
"libsixel" = "< 1.8.7+r1"
