security = true
must_match_all = false

[name]
default = "libssh 0.12.0"

[caution]
default = "Fixes 9 security vulnerabilities since 0.8.9 version"
zh_CN = "修复自 0.8.9 版本以来的 9 个安全漏洞"

[packages-v2]
"libssh" = "< 0.12.0"
"libssh+32" = "< 0.12.0"
