security = true

[name]
default = "libsoup 3.6.6"

[caution]
default = "Fixes 13 security vulnerabilities (including 3 of high severity)"
zh_CN = "修复 13 个安全漏洞（含 3 个高危漏洞）"

[packages-v2]
"libsoup-3" = "< 3.6.6"
