security = true
must_match_all = false

[name]
default = "libssh 0.12.1"

[caution]
default = "Fixes 12 security vulnerabilities (including 1 of high severity and 5 of medium severity)"
zh_CN = "修复 12 个安全漏洞（含 1 个高危漏洞和 5 个中危漏洞）"

[packages-v2]
"libssh" = "< 0.12.1"
"libssh+32" = "< 0.12.1"
