security = true

[name]
default = "libsixel 1.10.5"

[caution]
default = "Fixes a buffer overflow vulnerability (CVE-2021-40656, Severity: High), a null pointer dereference vulnerability (CVE-2021-45340, Severity: Medium), and stack-based buffer overflow vulnerability (CVE-2025-9300, Severity: Medium)"
zh_CN = "修复了一个缓冲区溢出漏洞（CVE-2021-40656，严重性：高）、一个空指针解引用漏洞（CVE-2021-45340，严重性：中），以及一个栈缓冲区溢出漏洞（CVE-2025-9300，严重性：中等）"

[packages-v2]
"libsixel" = "< 1.10.5"
