security = true

[name]
default = "libtpms 0.10.2"

[caution]
default = "Fixes an Use of a Broken or Risky Cryptographic Algorithm vulnerability (CVE-2026-21444, Severity: Medium)"
zh_CN = "修复一个使用了已损坏或存在风险的加密算法导致的漏洞（CVE-2026-21444，严重性：中）"

[packages-v2]
"libtpms" = "< 0.10.2"
