security = true

[name]
default = "libtpms 0.10.1"

[caution]
default = "Fixes a Out-of-Bounds Read vulnerability - CVE-2025-49133 (Severity: Medium)"
zh_CN = "修复一处越界读取 (Out-of-Bounds Read) 漏洞，漏洞编号 CVE-2025-49133（严重性：中）"

[packages-v2]
"libtpms" = "< 0.10.1"
