security = true

[name]
default = "LibTIFF 4.7.1"

[caution]
default = "Fixes 29 security vulnerabilities in LibTIFF since 2023 (8 of high severity)"
zh_CN = "修复自 2023 年以来在 LibTIFF 中披露的 29 处安全漏洞（含 8 个高危漏洞）"

[packages-v2]
libtiff = "< 4.7.1"
