security = true
must_match_all = false

[name]
default = "libtasn1 4.21.0"

[caution]
default = "Fixes a stack-based buffer overflow vulnerability - CVE-2025-13151 (Severity: High)"
zh_CN = "修复一个基于栈的缓冲区溢出漏洞，漏洞编号 CVE-2025-13151（严重性：高）"

[packages-v2]
"libtasn1" = "4.21.0"
"libtasn1+32" = "4.21.0"
