security = true

[name]
default = "libtommath 1.3.0"

[caution]
default = "Fixes a integer overflow vulnerabilities - CVE-2023-36328 (Severity: Critical)"
zh_CN = "修复一个整数溢出漏洞，漏洞编号 CVE-2023-36328（严重性：严重）"

[packages-v2]
"libtommath" = "< 1.3.0"
