security = true

[name]
default = "LibVNCServer 0.9.15"

[caution]
default = "Fixes a memory leak vulnerability (CVE-2020-29260, Severity: High), a heap out-of-bounds read vulnerability (CVE-2026-32853, Severity: High), and a NULL pointer dereference vulnerability (CVE-2026-32854, Severity: High)"
zh_CN = "修复了一个内存泄漏漏洞（CVE-2020-29260，严重性：高）、一个堆越界读取漏洞（CVE-2026-32853，严重性：高），以及一个空指针解引用漏洞（CVE-2026-32854，严重性：高）"

[packages-v2]
"libvncserver" = "< 0.9.15"
