security = true
must_match_all = false

[name]
default = "WebP Codec (libwebp) 1.6.0"

[caution]
default = "Fixes a Out-of-Bounds write vulnerability (CVE-2023-4863, Severity: High)"
zh_CN = "修复一个越界写入漏洞（CVE-2023-4863，严重性：高）"

[packages-v2]
"libwebp" = "< 1.6.0"
"libwebp+32" = "< 1.6.0"
