security = true
must_match_all = false

[name]
default = "libxml2 2.15.4"

[caution]
default = "Fixes 8 security vulnerabilities (1 of high severity and 5 of medium severity)"
zh_CN = "修复 8 个安全漏洞（含 1 个高危漏洞和 5 个中危漏洞）"

[packages-v2]
"libxml2" = "< 2.15.4"
"libxml2+32" = "< 2.15.4"
