security = true
must_match_all = false

[name]
default = "libxslt 1.1.43"

[caution]
default = "Fixes 2 use-after-free vulnerabilities - CVE-2025-24855, CVE-2024-55549 (Severity: High)"
zh_CN = "修复 2 个释放后使用 (use-after-free) 漏洞，漏洞编号 CVE-2025-24855, CVE-2024-55549（严重性：高）"

[packages-v2]
"libxslt" = "< 1.1.43"
"libxslt+32" = "< 1.1.43"
