security = true

[name]
default = "Linux PAM 1.7.1"
zh_CN = "Linux PAM 1.7.1"

[caution]
default = "Fixes two security vulnerabilities - CVE-2024-10963, CVE-2025-6020 (1 of high severity)"
zh_CN = "修复编号为 CVE-2024-10963 及 CVE-2025-6020 的安全漏洞（含 1 个高危漏洞）"

[packages]
"linux-pam" = "1.7.1"
