security = false

[name]
default = "Linux Kernel 6.18.7"
zh_CN = "Linux 内核，版本 6.18.7"

[caution]
default = "Include fix for incorrect processor topology reporting on Loongson 3B6000 platforms, fixes for AMD graphics and Intel HDA devices on SG2042/2044, as well as fix for boot failure on Loongson 2K2000 devices with older firmware"
zh_CN = "包含针对龙芯 3B6000 处理器拓扑报告错误、SG2042/2044 AMD 显卡及 Intel HDA 设备及搭载旧固件的龙芯 2K2000 引导故障的修复"

[packages-v2]
"linux+kernel" = "< 3:6.18.7"
