security = true

[name]
default = "Linux Kernel, 6.16.7"
zh_CN = "Linux 内核，版本 6.16.7"

[caution]
default = "Includes mitigation for VMSCAPE vulnerability for AMD, Hygon, and Intel platforms and fixes an issue where AMD Radeon RX 9000 may not correctly initialize on LoongArch and other hardware platforms"
zh_CN = "包含针对 AMD、Intel 及海光平台的 VMSCAPE 漏洞规避，并修复 AMD Radeon RX 9000 系列在龙架构等平台无法正确驱动的问题"

[packages]
"linux+kernel" = "3:6.16.7"
