security = false

[name]
default = "Linux Kernel 6.18"
zh_CN = "Linux 内核，版本 6.18"

[caution]
default = "Includes support for new devices and functionality fixes, adds preliminary support for CIX Technology's P1 (SKY1) SoCs, improves GPIO and CAN-FD bus support for Loongson 2K3000/3B6000M, Motorcomm YT6801 ethernet NIC, and the TH1520 SoC"
zh_CN = "包含大量新设备支持及功能修复，新增此芯科技 P1 (SKY1) SoC 的初始支持，改善龙芯 2K3000/3B6000M GPIO 及 CAN-FD 总线、裕太微 YT6801 以太网卡及 TH1520 SoC 的支持"

[packages-v2]
"linux+kernel" = "< 3:6.18.7"
