security = false

[name]
default = "Linux Kernel, 6.14.4"
zh_CN = "Linux 内核，版本 6.14.4"

[caution]
default = "Fixes S0ix suspend failure on MECHREVO Wujie 14X"
zh_CN = "修复机械革命无界 14X 笔记本 S0ix 睡眠失败的问题"

[packages]
"linux-kernel-6.14.4" = "6.14.4-1"
"linux+kernel" = "3:6.14.4"
