security = false

[name]
default = "Linux Kernel 7.1.5-2"
zh_CN = "Linux 内核，版本 6.17.7-2"

[caution]
default = "Introduces support for i486 (Afterglow) and a pre-upstream version of LoongArch CPU/SoC dynamic frequency and voltage scaling driver"
zh_CN = "新增 i486（星霞 OS）支持，并引入了预上游版本的龙架构处理器/SoC 动态调频调压驱动"

[packages-v2]
"linux-kernel-7.1.5" = "< 7.1.5-2"
