security = true

[name]
default = "Linux Kernel (Apple silicon) 6.18.27"
zh_CN = "Linux 内核 (Apple silicon)，版本 6.18.27"

[caution]
default = "Fixes a series of Local Privilege Escalation vulnerability, codenamed \"Dirty Frag\" (severity: High)"
zh_CN = "修复代号为 \"Dirty Frag\" 的系列本地提权漏洞（严重性：高）"

[packages-v2]
"linux+kernel+asahi" = "< 3:6.18.27"
