security = false

[name]
default = "Linux Kernel, 6.14.11-2"
zh_CN = "Linux 内核，版本 6.14.11-2"

[caution]
default = "Add support for the Ethernet GMAC on the Loongson 2K3000 SoC"
zh_CN = "新增龙芯 2K3000 片上以太网 GMAC 设备的支持"

[packages]
"linux+kernel" = "3:6.14.11-2"
"linux-kernel-6.4.11" = "6.14.11-1"
