security = false

[name]
default = "Linux Kernel (Longterm Maintenance), 6.12.29 (revision 2)"
zh_CN = "Linux 内核（长期维护版本），版本 6.12.29（修订 2）"

[caution]
default = "Fixes an issue where display brightness on Loongson 3A5000/6000-based laptops may be reset to the lowest upon wakeup from S3 suspend"
zh_CN = "修复基于龙芯 3A5000/3A6000 的笔记本从 S3 睡眠唤醒时，屏幕背光亮度可能被复位为最低的问题"

[packages]
"linux-kernel-lts-6.12.31" = "6.12.31-2"
