security = false

[name]
default = "Linux Kernel 6.18.16"
zh_CN = "Linux 内核，版本 6.18.16"

[caution]
default = "Fixes kernel crashes during boot up on Zhaoxin C4600-based devices and drivers crashes with AMD RDNA 3-based GPUs on LoongArch devices"
zh_CN = "修复兆芯 C-4600 设备启动时内核崩溃及龙架构平台使用 AMD RDNA 3 显卡时偶发驱动崩溃的问题"

[packages-v2]
"linux+kernel" = "< 3:6.18.16"
