security = false

[name]
default = "Linux Kernel 6.18.8"
zh_CN = "Linux 内核，版本 6.18.8"

[caution]
default = "Include fixes for Loongson 7A GMAC (Ethernet NIC), laptop internal keyboards, and O32 applications on Loongson 3 (MIPS) devices"
zh_CN = "包含针对龙芯三号 (MIPS) 设备上的龙芯 7A GMAC（以太网接口）、笔记本内置键盘及 O32 应用程序的修复"

[packages-v2]
"linux+kernel" = "< 3:6.18.8"
