security = false

[name]
default = "Linux Kernel (Longterm Maintenance), 6.12.32"
zh_CN = "Linux 内核（长期维护版本），版本 6.12.32"

[caution]
default = "Fixes an issue where display brightness on Loongson 3A5000/6000-based laptops may be reset to the lowest upon wakeup from S3 suspend, also works around incorrectly configured supported link speed on PCIe bridges found on older Loongson 3C6000 series steppings, causing degraded performance or functionalities on certain peripherals"
zh_CN = "修复基于龙芯 3A5000/3A6000 的笔记本从 S3 睡眠唤醒时，屏幕背光亮度可能被复位为最低的问题，并规避较老的龙芯 3C6000 系列处理器步进上 PCIe 桥未正确设置支持链路速率而导致部分设备性能和功能受限的问题"

[packages]
"linux+kernel+lts" = "2:6.12.32"
