security = false

[name]
default = "Linux Kernel, 6.17.7-2"
zh_CN = "Linux 内核，版本 6.17.7-2"

[caution]
default = "Disables VIA PadLock hardware cryptographic engine on ZhaoXin KaiXian KX-6000/6000G platforms to fix a crash during initramfs generation, also adds workaround for a boot-time warning"
zh_CN = "在兆芯开先 KX-6000/6000G 平台上禁用 VIA PadLock 硬件密码学引擎以修复生成初始内存盘 (initramfs) 时的崩溃问题，并规避一处启动时警告"

[packages-v2]
"linux-kernel-6.17.7" = "< 6.17.7-1"
