security = false

[name]
default = "Linux Kernel, 6.16.0"
zh_CN = "Linux 内核，版本 6.16.0"

[caution]
default = "Includes support for new devices and functionality fixes, introduces 16KiB/4KiB-paged dual kernels for LoongArch, fixes an issue with some Lenovo ThinkBook models, where FnLock and backlight settings were incorrectly reset upon reboot, as well as fixes for incorrect mute thresholds for certain USB audio devices, KVM instability on Loongson 3B6000/3C6000 platforms, and backlight control for Loongson 3A5000/3A6000-based laptops; introduce additionally AMDGPU KFD support for LoongArch and RISC-V devices, as well as initial support for SG2042/2044 platforms"
zh_CN = "包含大量新设备支持及功能修复，为龙架构引入 16KiB/4KiB 分页双内核功能、修复部分 Lenovo ThinkBook 型号 FnLock 及背光在重启后被错误复位的问题，修复部分 USB 音频设备静音阈值设置错误的问题，修复龙芯 3B6000/3C6000 家族 KVM 客户机稳定性问题，修复龙芯 3A5000/3A6000 笔记本电脑屏幕背光调整功能，为龙架构及 RISC-V 启用 AMDGPU KFD（异构计算）支持，并引入 SG2042/2044 平台初步支持"

[packages]
"linux+kernel" = "3:6.16.4"
