security = true

[name]
default = "Linux Kernel 6.18.25"
zh_CN = "Linux 内核，版本 6.18.25"

[caution]
default = "Fixes a Local Privilege Escalation vulnerability (\"Copy Fail\") - CVE-2026-31431 (severity: High)"
zh_CN = "修复一个本地提权漏洞 (\"Copy Fail\") ，漏洞编号 CVE-2026-31431（严重性：高）"

[packages-v2]
"linux+kernel" = "< 3:6.18.25"
