security = false

[name]
default = "Linux Kernel 6.17"
zh_CN = "Linux 内核，版本 6.17"

[caution]
default = "Includes support for new devices and functionality fixes, improves the practicality of kernel panic screens"
zh_CN = "包含大量新设备支持及功能修复，改善内核崩溃 (Kernel Panic) 界面的实用性"

[packages-v2]
"linux+kernel" = "< 3:6.17.0"
