security = false
must_match_all = false

[name]
default = "Device Driver Firmware and Microcode Update (February 21, 2026)"
zh_CN = "设备驱动固件及微码更新（2026 年 2 月 21 日）"

[caution]
default = "With enhancements for various audio, graphics, networking, and SoC devices and platforms, notably firmware for Intel Image Processing Unit 7, enabling webcam support for Intel Panther Lake-based devices"
zh_CN = "包含对数款音频、图形和网络设备，以及 SoC 平台的支持增强，新增 Intel Image Processing Unit 7 的固件，可用于启用 Intel Panther Lake 设备摄像头的支持"

[packages-v2]
"firmware-nonfree" = "< 20260221+debian20260110+1"
