security = false

[name]
default = "Linux Kernel (Longterm Maintenance), 6.12.34"
zh_CN = "Linux 内核（长期维护版本），版本 6.12.34"

[caution]
default = "Fixes an issue where the display output on Intel Skylake devices may flicker off when IOMMU is enabled and where the touchpads on Loongson 3A6000-based laptops (IPASON NL38-N11 and possibly others) are non-functional"
zh_CN = "修复 Intel Skylake 设备上启用 IOMMU 特性后显示输出时有闪黑的问题，并修复龙芯 3A6000 笔记本（如攀升 NL38-N11 及其他型号）触摸板不可用的问题"

[packages]
"linux+kernel+lts" = "2:6.12.34"
