security = false
must_match_all = false

[name]
default = "Linux Firmware Update (April 25, 2025)"
zh_CN = "Linux 固件更新（2025 年 4 月 25 日）"

[caution]
default = "With enhancements for various audio, graphics, networking, and SoC devices and platforms, and a fix for unusable Wi-Fi on REDMI Book Pro 14 2025"
zh_CN = "包含对数款音频、图形和网络设备，以及 SoC 平台的支持增强，并修复 REDMI Book Pro 14 2025 上无线网络不可用的问题"

[packages]
"firmware-nonfree" = "20250425+debian20241210+1~bpo12+1"
