security = false
must_match_all = false

[name]
default = "Linux Kernel 7.1.13"
zh_CN = "Linux 内核，版本 7.1.13"

[caution]
default = "Fixes spurious Motorcomm YT6801 link up issue, i8042 PS/2 keyboard/mouse controller initialisation on device-tree-based MIPS Loongson platforms, kernel log floods on laptops with Hantick 5288 touchpads, as well as screen orientation on more GPD Pocket 4 variants; also enable USB_DUMMY_HCD for development purpose, as well as various essential features (such as ThinkPad ACPI Extras and initramfs compression support) for i486"
zh_CN = "修复裕太微 (Motorcomm) YT6801 以太网卡偶发链路启用问题、基于设备树的 MIPS 龙芯三号平台上 i8042 PS/2 键鼠控制器无法初始化的问题、搭载瀚天鑫 (Hantick) 5288 触摸板的笔记本上内核大量异常输出的问题，并将 GPD Pocket 4 系列的屏幕朝向问题规避适配到更多同系列型号上；此外，还根据用户反馈开启了服务开发用途的 USB_DUMMY_HCD 选项，并为 i486 开启了数个重要特性（如 ThinkPad ACPI Extras 及初始化内存盘压缩支持）"

[packages-v2]
"linux+kernel" = "< 3:7.1.13"
