security = true
must_match_all = false

[name]
default = "Linux Kernel 7.0.13"
zh_CN = "Linux 内核，版本 7.0.13"

[caution]
default = "Fixes a Local Privilege Escalation vulnerability, codenamed \"pedit COW\" or \"PACKET_EDIT_MEME.c\" (CVE-2026-46331, severity: High)"
zh_CN = "修复代号为 \"pedit COW\"（又名 \"PACKET_EDIT_MEME.c\"）的本地提权漏洞（CVE-2026-46331，严重性：高）"

[packages-v2]
"linux+kernel" = "< 3:7.0.13"
