security = false

[name]
default = "Linux Kernel 7.1"
zh_CN = "Linux 内核，版本 7.1"

[caution]
default = "Includes support for new devices and functionality fixes and, additionally, introduces a workaround for backlight enablement on S3 wakeup on Loongson 3B6000M laptop (EAECIS NL60R) and a fix for touchpads on certain Loongson 3A6000 laptop models (Lenovo KaiTian N60d and Inspur CP300L3)"
zh_CN = "包含大量新设备支持及功能修复，较为重要的更新包括规避龙芯 3B6000M 笔记本（卓怡恒通 NL60R）S3 唤醒时无法启用背光的问题，并修复了部分龙芯 3A6000 笔记本型号（联想开天 N60d 及浪潮英政 CP300L3）触摸板无法使用的问题"

[packages-v2]
"linux+kernel" = "< 3:7.1.5"
