security = true

[name]
default = "Linux Kernel, 6.14.7"
zh_CN = "Linux 内核，版本 6.14.7"

[caution]
default = "Fixes self-training Spectre-v2/Spectre-BHB (Exposure of Sensitive Information) vulnerability for various x86 and Arm platforms, also fixes wrong processor topology setting for Loongson 3A6000/3B6000/3C6000 series processors"
zh_CN = "包含针对数个 x86 及 Arm 平台的 Spectre-v2/Spectre-BHB（敏感信息泄漏）漏洞修复，并修复龙芯 3A6000/3B6000/3C6000 系列处理器下处理器拓扑设置错误的问题"

[packages]
"linux+kernel" = "3:6.14.7"
