security = false

[name]
default = "Linux Kernel, 6.17.7-4"
zh_CN = "Linux 内核，版本 6.17.7-4"

[caution]
default = "Fixes an issue where non-Latin paths and filenames in NTFS partitions could not be read on AArch64, Loongson 3 (MIPS), and RISC-V systems"
zh_CN = "修复 AArch64、龙芯三号 (MIPS) 及 RISC-V 平台无法正确读取 NTFS 分区中非拉丁路径及文件名的问题"

[packages-v2]
"linux-kernel-6.17.7" = "< 6.17.7-4"
