security = false

[name]
default = "Linux Kernel 7.1.9"
zh_CN = "Linux 内核，版本 7.1.9"

[caution]
default = "Adds ThinkPad ACPI support to i486"
zh_CN = "为 i486 系统新增 ThinkPad ACPI 支持"

[packages-v2]
"linux+kernel" = "< 3:7.1.9"
