security = true
must_match_all = false

[name]
default = "Linux Kernel 7.1.7"
zh_CN = "Linux 内核，版本 7.1.7"

[caution]
default = "Fixes a KVM escape vulnerability, codenamed \"Zapscape\" (CVE-2026-64561, severity: High)"
zh_CN = "修复代号为 \"Zapscape\" 的 KVM 逃逸漏洞（CVE-2026-64561，严重性：高）"

[packages-v2]
"linux+kernel" = "< 3:7.1.7"
