security = false

[name]
default = "Linux Kernel (Longterm Maintenance), 6.12.26"
zh_CN = "Linux 内核（长期维护版本），版本 6.12.26"

[caution]
default = "Fixes CJK character display in virtual terminal in HiDPI displays and enables basic display support via firmware"
zh_CN = "修复高分屏下虚拟终端 CJK（中文、日文及韩文）字符显示错误的问题，并开启基于固件的基础显示支持"

[packages]
"linux+kernel+lts" = "2:6.12.26"
