security = true

[name]
default = "lrzip 0.660"

[caution]
default = "Fixes denial of service vulnerabilities (CVE-2022-33067, CVE-2023-39741, Severity: Medium), a use-after-free vulnerability (CVE-2025-15570, Severity: High), and a null pointer dereference vulnerability (CVE-2025-15571, Severity: Medium)"
zh_CN = "修复拒绝服务漏洞（CVE-2022-33067、CVE-2023-39741，严重性：中）、一个释放后使用漏洞（CVE-2025-15570，严重性：高）和一个空指针解引用漏洞（CVE-2025-15571，严重性：中）"

[packages-v2]
"lrzip" = "< 0.660"
