security = true

[name]
default = "LXC 7.0.0"

[caution]
default = "Fixes a network configuration permission vulnerability in lxc-user-nic when used with OVS - CVE-2026-39402 (Severity: Low)"
zh_CN = "修复一个 lxc-user-nic 与 OVS 配合使用时存在的网络配置权限漏洞, 漏洞编号 CVE-2026-39402 (严重性: 低)"

[packages-v2]
"lxc" = "< 7.0.0"
