security = true

[name]
default = "lxml 6.1.0"

[caution]
default = "Fixes an Improper Restriction of XML External Entity Reference vulnerability (CVE-2026-41066, Severity: High)"
zh_CN = "修复一个 XML 外部实体引用的不恰当限制漏洞（CVE-2026-41066，严重性：高）"

[packages-v2]
"lxml" = "< 6.1.0"
