security = true

[name]
default = "mako 1.3.12"

[caution]
default = "Fixes a Path Traversal vulnerability (CVE-2026-41205, Severity: High)"
zh_CN = "修复一个路径遍历漏洞（CVE-2026-41205，严重性：高）"

[packages-v2]
"mako" = "< 1.3.12"
