security = true

[name]
default = "MariaDB 12.3.1"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability (CVE-2026-32710, Severity: Critical) and a Memory Allocation with Excessive Size Value vulnerability (CVE-2026-35549, Severity: Medium)"
zh_CN = "修复一个堆缓冲区溢出漏洞（CVE-2026-32710，严重性：严重）和一个未经控制的内存分配漏洞（CVE-2026-35549，严重性：中）"

[packages-v2]
"mariadb" = "< 12.3.1"
