security = true

[name]
default = "MathJax 4.1.0"
zh_CN = "MathJax 4.1.0"

[caution]
default = "Fixes two Regular expression Denial of Service (ReDoS) vulnerabilities - CVE-2023-39663 (Severity: High)"
zh_CN = "修复两个正则表达式拒绝服务（ReDoS）漏洞，漏洞编号 CVE-2023-39663（严重性：高）"

[packages-v2]
"mathjax" = "<2.7.9"
