security = true

[name]
default = "MATIO 1.5.30"

[caution]
default = "Fixes 2 buffer overflow vulnerabilities (CVE-2025-2337 and CVE-2025-2338, Severity: Medium) and a heap memory corruption vulnerability (CVE-2025-50343, Severity: Unknown)"
zh_CN = "修复 2 个缓冲区溢出漏洞（CVE-2025-2337 和 CVE-2025-2338，严重性：中）和一个堆内存损坏漏洞（CVE-2025-50343，严重性：未知）"

[packages-v2]
"matio" = "< 1.5.30"
