security = true

[name]
default = "Mbed TLS 3.6.6"

[caution]
default = "Fixes 4 security vulnerabilities (including 3 of high severity and 1 of medium severity)"
zh_CN = "修复 4 个安全漏洞（含 3 个高危漏洞, 1 个中危漏洞）"

[packages-v2]
"mbedtls" = "< 3.6.6"
"mbedtls+32" = "< 3.6.6"
