security = true

[name]
default = "Mercurial 6.9.4 Security Update"
zh_CN = "Mercurial 6.9.4 安全更新"

[caution]
default = "Fixes a cross-site scripting (XSS) vulnerability - CVE-2025-2361 (Severity: Moderate)"
zh_CN = "本更新可修复一处跨站脚本攻击 (XSS)，漏洞编号 CVE-2025-2361（严重性：中等）"

[packages]
mercurial = "6.9.4"
