security = true

[name]
default = "Mihomo 1.19.11 Security Update"
zh_CN = "Mihomo 1.19.11 安全更新"

[caution]
default = "Fixes 2 cases of local permission escalation vulnerability"
zh_CN = "修复 2 例本地提权漏洞"

[packages]
mihomo = "1.19.11-1"
