security = true

[name]
default = "miniupnpd 2.3.10"

[caution]
default = "Fixes an Integer Underflow vulnerability (CVE-2026-5720, Severity: Critical)"
zh_CN = "修复一个整数下溢漏洞（漏洞编号 CVE-2026-5720，严重性：严重）"

[packages-v2]
"miniupnpd" = "< 2.3.10"
