security = true

[name]
default = "mitmproxy 12.2.2"

[caution]
default = "Fixes an LDAP injection vulnerability (CVE-2026-40606, Severity: Medium)"
zh_CN = "修复一个 LDAP 注入漏洞（CVE-2026-40606，严重性：中）"

[packages-v2]
"mitmproxy" = "< 12.2.2+rs0.12.9"
