security = true

[name]
default = "MKVToolNix 102.0"

[caution]
default = "Fixes an Integer Overflow to Buffer Overflow vulnerability (Severity: High, CVE-2026-90783)"
zh_CN = "修复 1 个整数溢出导致的缓冲区溢出漏洞（严重性：高，CVE-2026-90783）"

[packages-v2]
"mkvtoolnix" = "< 102.0"
