security = true

[name]
default = "MuPDF 1.27.2"

[caution]
default = "Fixes a double-free vulnerability - CVE-2026-25556 (Severity: High)"
zh_CN = "修复一个双重释放漏洞，漏洞编号 CVE-2026-25556（严重性：高）"

[packages-v2]
"mupdf" = "< 1:1.27.2"
