security = true

[name]
default = "mupdf 1.27.0"

[caution]
default = "Fixes a denial of service vulnerability (CVE-2025-46206, Severity: Medium) and a null pointer dereference vulnerability (CVE-2025-55780, Severity: High)"
zh_CN = "修复一处拒绝服务漏洞（CVE-2025-46206，严重性：中）和一处空指针解引用漏洞（CVE-2025-55780，严重性：高）"

[packages-v2]
"mupdf" = "< 1.27.0"
