security = true

[name]
default = "Mini-XML 3.3.1"

[caution]
default = "Fixes a memory leak vulnerabilities (Severity: High) and a buffer overflow vulnerabilities (Severity: High)"
zh_CN = "修复一个内存泄漏漏洞（严重性：高）和一个缓冲区溢出漏洞（严重性：高）"

[packages-v2]
"mxml" = "< 3.3.1"
