security = true

[name]
default = "Net-SNMP 5.9.5.2"

[caution]
default = "Fixes a buffer overflow vulnerability - CVE-2025-68615 (Severity: Critical)"
zh_CN = "修复一个缓冲区溢出漏洞，漏洞编号 CVE-2025-68615（严重性：严重）"

[packages-v2]
"net-snmp" = "< 5.9.5.2"
