security = true

[name]
default = "NetHack 5.0.0"

[caution]
default = "Fixes a Buffer Copy without Checking Size of Input vulnerabilities (CVE-2023-24809, Severity: Medium)"
zh_CN = "修复 1 个缓冲区复制时未检查输入大小的漏洞（CVE-2023-24809，严重性：中）"

[packages-v2]
"nethack" = "< 5.0.0"
