security = true

[name]
default = "nghttp2 1.70.0"

[caution]
default = "Fixes a HTTP Request/Response Smuggling vulnerability (CVE-2026-58055, Severity: Medium)"
zh_CN = "修复 1 个 HTTP 请求/响应欺骗漏洞（CVE-2026-58055，严重性：中）"

[packages-v2]
"nghttp2" = "< 1.70.0"
