security = true

[name]
default = "nghttp2 1.69.0"

[caution]
default = "Fixes a Reachable Assertion vulnerability (CVE-2026-27135, Severity: High)"
zh_CN = "修复一个可达断言漏洞（CVE-2026-27135，严重性：高）"

[packages-v2]
"nghttp2" = "< 1.69.0"
