security = true

[name]
default = "nginx 1.30.2"

[caution]
default = "Fixes a buffer overflow vulnerability (CVE-2026-9256, Severity: Critical)"
zh_CN = "修复一个缓冲区溢出漏洞（CVE-2026-9256，严重性：严重）"

[packages-v2]
"nginx" = "< 1.30.2"
