security = true

[name]
default = "nginx 1.30.4"

[caution]
default = "Fixes 3 security vulnerabilities disclosed in F5 Security Advisory on Jul 15, 2026 (including 1 of Critical severity)"
zh_CN = "修复 F5 在 2026 年 7 月 15 日发布的安全公告中披露的 3 个安全漏洞（含 1 个严重漏洞）"

[packages-v2]
"nginx" = "< 1.30.4"
