security = true

[name]
default = "nginx 1.31.3"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability (CVE-2026-42533, Severity: Critical)"
zh_CN = "修复 1 个堆缓冲区溢出漏洞（CVE-2026-42533，严重性：严重）"

[packages-v2]
"nginx" = "< 1.31.3"
