security = true

[name]
default = "Node.js 22.22.2"

[caution]
default = "Fixes 7 security vulnerabilities disclosed in March 24, 2026 Security Releases (2 of high severity)"
zh_CN = "修复 2026 年 3 月 24 日安全更新公告中披露的 7 个安全漏洞（含 2 个高危漏洞）"

[packages]
"nodejs-22" = "22.22.2"
