security = true

[name]
default = "Node.js 24.18.1"

[caution]
default = "Fixes 11 security vulnerabilities disclosed in July 29, 2026 Security Releases (3 of high severity)"
zh_CN = "修复 2026 年 7 月 29 日安全更新公告中披露的 11 个安全漏洞（含 3 个高危漏洞）"

[packages-v2]
"nodejs-24" = "< 24.18.1"
