security = true

[name]
default = "Node.js 24.17.0"

[caution]
default = "Fixes 11 security vulnerabilities disclosed in June 18, 2026 Security Releases (2 of high severity)"
zh_CN = "修复 2026 年 6 月 18 日安全更新公告中披露的 11 个安全漏洞（含 2 个高危漏洞）"

[packages]
"nodejs-24" = "< 24.17.0"
