security = true

[name]
default = "Node.js 26.5.1"

[caution]
default = "Fixes 10 security vulnerabilities disclosed in July 29, 2026 Security Releases (2 of high severity)"
zh_CN = "修复 2026 年 7 月 29 日安全更新公告中披露的 10 个安全漏洞（含 2 个高危漏洞）"

[packages-v2]
"nodejs-26" = "< 26.5.1"
