security = true

[name]
default = "Node.js 24.14.1"

[caution]
default = "Fixes 8 security vulnerabilities disclosed in March 24, 2026 Security Releases (2 of high severity)"
zh_CN = "修复 2026 年 3 月 24 日安全更新公告中披露的 8 个安全漏洞（含 2 个高危漏洞）"

[packages]
"nodejs-24" = "24.14.1"
