security = true

[name]
default = "Node.js 20.19.2"

[caution]
default = "Fixes 3 security vulnerabilities disclosed in May 14, 2025 Security Releases (1 of high severity)"
zh_CN = "修复 2025 年 5 月 14 日安全更新公告中披露的 3 个安全漏洞（含 1 个高危漏洞）"

[packages]
"nodejs-20" = "20.19.2"
