security = true

[name]
default = "NSD 4.15.2"

[caution]
default = "Fixes 4 security vulnerabilities (including 3 of High Severity and 1 of Medium Severity)"
zh_CN = "修复 4 个安全漏洞（含 3 个高危漏洞和 1 个中危漏洞）"

[packages-v2]
"nsd" = "< 4.15.2"
