security = true

[name]
default = "NLnet Labs Name Server Daemon 4.14.3"
zh_CN = "NLnet Labs 名称服务器守护程序 4.14.3"

[caution]
default = "Fixes 4 security vulnerabilities (4 of High severity)"
zh_CN = "修复 4 个安全漏洞（含 4 个高危漏洞）"

[packages-v2]
"nsd" = "< 4.14.3"
