security = true
must_match_all = false

[name]
default = "NTFS-3G 2026.7.7"

[caution]
default = "Fixes 9 security vulnerabilities (severity details pending)"
zh_CN = "修复 9 个安全漏洞（漏洞严重性细节待定）"

[packages-v2]
"ntfs-3g" = "< 1:2026.7.7"
