security = true

[name]
default = "NTFS-3G 2026.9.18"

[caution]
default = "Fixes 8 security vulnerabilities (including 5 of Medium Severity and 3 of Low Severity)"
zh_CN = "修复 8 个安全漏洞（含 5 个中危漏洞和 3 个低危漏洞）"

[packages-v2]
"ntfs-3g" = "< 1:2026.9.18"
