security = true
must_match_all = false

[name]
default = "NTFS-3G 2026.7.7"

[caution]
default = "Fixes 9 security vulnerabilities (including 7 of high severity and 2 of moderate severity)"
zh_CN = "修复 9 个安全漏洞（含 7 个高危漏洞, 2 个中危漏洞）"

[packages-v2]
"ntfs-3g" = "< 1:2026.7.7"
