security = true

[name]
default = "nvm 0.40.5"

[caution]
default = "Fix two command injection vulnerabilities (CVE-2026-10796, severity: High; CVE-2026-1665, severity: Medium)"
zh_CN = "修复了两个命令注入漏洞（CVE-2026-10796，严重性：高；CVE-2026-1665，严重性：中）"

[packages-v2]
"nvm" = "< 0.40.5"
