security = true
must_match_all = false

[name]
default = "oma 1.25.2"
zh_CN = "小熊猫包管理 (oma) 1.25.2"

[caution]
default = "Fixes a Improper Neutralization of CRLF Sequences vulnerability (Severity: Low)"
zh_CN = "修复一个 CRLF 序列处理不当漏洞（严重性：低）"

[packages-v2]
"oma" = "< 1.25.2"
