security = false
must_match_all = false

[name]
default = "oma 1.21.0"
zh_CN = "小熊猫包管理 (oma) 1.21.0"

[caution]
default = "With localized help messages and man pages, as well as protection against removal of currently running kernels, fixes for the why command, OSC 9;4 terminal progress reporting, and more"
zh_CN = "新增帮助信息及手册本地化，以及使用中内核保护功能、why 命令修复及 OSC 9;4 终端进度反馈等新特性"

[packages]
oma = "1.21.0"
