security = false
must_match_all = false

[name]
default = "oma 1.25"
zh_CN = "小熊猫包管理 (oma) 1.25"

[caution]
default = "Introduces Y/N confirmation mode and improves user interfaces and lock behavior"
zh_CN = "新增 Y/N 确认操作模式、改善部分用户界面并优化实例锁行为"

[packages-v2]
"oma" = "< 1.25.0"
