security = false
must_match_all = false

[name]
default = "oma 1.23.1"
zh_CN = "小熊猫包管理 (oma) 1.23.1"

[caution]
default = "Improves compatibility with APT's `Optional' configuration for repository metadata, fixing metadta refreshing with CrowdSec's repository (and maybe others), also fixes path completion for `oma provides'"
zh_CN = "增强对 APT `Optional' 配置字段的兼容性，修复无法从 CrowdSec 等软件源刷新元数据的问题，并为 `oma provides' 命令添加了路径补全功能"

[packages-v2]
"oma" = "< 1.23.1"
