security = false
must_match_all = false

[name]
default = "oma 1.26"
zh_CN = "小熊猫包管理 (oma) 1.26"

[caution]
default = "Improves HTTP download performance and compatibility, and introduces automatic cleaning after system updates and package installation"
zh_CN = "改善 HTTP 下载性能和兼容性并引入了软件包更新和安装后的自动清理功能"

[packages-v2]
"oma" = "< 1.26.0"
