security = false
must_match_all = false

[name]
default = "oma 1.17.2"
zh_CN = "小熊猫包管理 (oma) 1.17.2"

[caution]
default = "With newly introduced disk usage analyzer, low storage warning, Zsh shell completions, and more"
zh_CN = "包含全新磁盘占用分析器、磁盘将满警告、Zsh 补全等新特性"

[packages]
oma = "1.17.2"
