security = false
must_match_all = false

[name]
default = "oma 1.27"
zh_CN = "小熊猫包管理 (oma) 1.27"

[caution]
default = "Includes an interface for the history and undo subcommands, as well as accelerated searching and command-not-found prompts powered by the amo D-Bus service"
zh_CN = "包含全新历史 (oma history) 及撤销 (oma undo) 界面，引入 D-Bus 服务 amo 加速搜索及未知命令提示"

[packages-v2]
"oma" = "< 1.27.1"
