security = false
must_match_all = false

[name]
default = "oma 1.18.0"
zh_CN = "小熊猫包管理 (oma) 1.18.0"

[caution]
default = "With newly introduced why and tree commands for dependency tree analysis, enhancements to the package metadata viewer (oma show), and fixes and improvements to the user interface"
zh_CN = "引入用于依赖树分析的 tree 及 why 命令，增强软件包信息查阅功能 (oma show)，优化现有界面操作逻辑进行优化，并修复了数个细节问题"

[packages]
oma = "1.18.0"
