security = false
must_match_all = false

[name]
default = "oma 1.24"
zh_CN = "小熊猫包管理 (oma) 1.24"

[caution]
default = "Improves compatibility with APT's cryptography policies and enhances logging performance with spdlog-rs"
zh_CN = "增强对 APT 密码学算法策略的兼容性并通过引入 spdlog-rs 改善日志性能"

[packages-v2]
"oma" = "< 1.24.1"
