security = false
must_match_all = false

[name]
default = "oma 1.16.0"
zh_CN = "小熊猫包管理 (oma) 1.16.0"

[caution]
default = "With improved interface and instructions for fixing/reporting package manager errors, topic-aware undo functionality, and enhancements to various interfaces."
zh_CN = "修缮了软件包管理报错及修复操作的用户界面、为撤销功能 (oma undo) 新增了对安同 OS 测试源 (topics) 设置的状态操作支持，并对一部分界面设计进行了优化"

[packages]
oma = "1.16.0"
