security = true

[name]
default = "OpenVPN 2.6.14 Security Update"
zh_CN = "OpenVPN 2.6.14 安全更新"

[caution]
default = "Fixes a denial of service vulnerability - CVE-2025-2704 (Severity: Medium)"
zh_CN = "修复一处拒绝服务漏洞，漏洞编号 CVE-2025-2704（严重性：中）"

[packages]
openvpn = "2.6.14"
