security = true
must_match_all = false

[name]
default = "OpenSSL 1.1.1zh"

[caution]
default = "Fixes 5 security vulnerabilities disclosed in OpenSSL Security Advisory on June 9, 2026 (including 1 of Critical and 3 of High severity)"
zh_CN = "修复 OpenSSL 在 2026 年 6 月 9 日发布的安全公告中披露的 5 个安全漏洞（含 1 个严重漏洞和 3 个高危漏洞）"

[packages-v2]
"openssl-1.1" = "< 1.1.1zh"
"openssl-1.1+32" = "< 1.1.1zh"
