security = true

[name]
default = "OpenJFX 21.0.12"

[caution]
default = "Fixes 11 security vulnerabilities not yet publicly disclosed"
zh_CN = "修复 11 个暂未公开的安全漏洞"

[packages-v2]
openjfx-21 = "< 21.0.12+3"
