security = true
must_match_all = false

[name]
default = "OpenJDK Security Updates (April, 2025)"
zh_CN = "OpenJDK 安全更新（2025 年 4 月）"

[caution]
default = "Fixes over 20 security vulnerabilities disclosed in Oracle Critical Patch Update Advisory - April 2025 (multiple of high severity)"
zh_CN = "修复 Oracle 重要更新公告（2025 年 4 月）中披露的逾 20 个安装漏洞（含多个高危漏洞）"

[packages]
"openjdk-8" = "8u452+ga"
"openjdk-11" = "11.0.27+ga"
"openjdk-17" = "17.0.15+ga"
"openjdk-21" = "21.0.7+ga"
"openjdk-24" = "24.0.1+ga"
