security = true
must_match_all = false

[name]
default = "OpenSSL 1.1.1ze"

[caution]
default = "The OpenSSL project no longer provides free security updates to OpenSSL v1.1.1 - this update switches to a third-party maintained fork, which fixes numerous security vulnerabilities since OpenSSL 1.1.1w (released in 2024)"
zh_CN = "因 OpenSSL 官方不再提供针对 v1.1.1 分支的免费安全更新，本更新改用第三方维护的源代码；修复自 2024 年以来在 OpenSSL 1.1.1w 中发现的若干安全漏洞"

[packages-v2]
"openssl-1.1" = "< 1.1.1ze"
"openssl-1.1+32" = "< 1.1.1ze"
