security = true

[name]
default = "OpenList 4.1.10"

[caution]
default = "Fixes a path traversal vulnerability - CVE-2026-25059 (Severity: High); Fixes an insecure TLS default configuration vulnerability - CVE-2026-25060 (Severity: High)"
zh_CN = "修复一处路径遍历漏洞，漏洞编号 CVE-2026-25059（严重性：高）；修复一处 TLS 默认配置漏洞，漏洞编号 CVE-2026-25060（严重性：高）"

[packages-v2]
"openlist" = "< 4.1.10"
