security = true

[name]
default = "OpenSC 0.27.1"

[caution]
default = "Fixes 5 security vulnerabilities (including 5 of medium severity)"
zh_CN = "修复 5 个安全漏洞（含 5 个中危漏洞）"

[packages-v2]
"opensc" = "< 0.27.1"
