security = true
must_match_all = false

[name]
default = "OpenSSL 3.6.2"

[caution]
default = "Fixes 8 security vulnerabilities disclosed in OpenSSL Security Advisory on March 13, 2026 and April 7, 2026 (2 of high severity)"
zh_CN = "修复 OpenSSL 在 2026 年 3 月 13 日和 2026 年 4 月 7 日发布的安全公告中披露的 8 个安全漏洞（含 2 个高危漏洞）"

[packages-v2]
"openssl" = "< 3.6.2"
"openssl+32" = "< 3.6.2"
