security = true
must_match_all = false

[name]
default = "OpenSSL 3.6.4"

[caution]
default = "Fixes 11 security vulnerabilities disclosed in OpenSSL Security Advisory on August 25, 2026 (including 3 of Medium severity)"
zh_CN = "修复 OpenSSL 在 2026 年 8 月 25 日发布的安全公告中披露的 11 个安全漏洞（含 3 个中危漏洞）"

[packages-v2]
"openssl" = "< 3.6.4"
"openssl+32" = "< 3.6.4"
