security = true
must_match_all = false

[name]
default = "OpenSSL 3.6.3"

[caution]
default = "Fixes 18 security vulnerabilities disclosed in OpenSSL Security Advisory on June 9, 2026 (including 1 of High and 5 of Medium severity)"
zh_CN = "修复 OpenSSL 在 2026 年 6 月 9 日发布的安全公告中披露的 18 个安全漏洞（含 1 个高危漏洞和 5 个中危漏洞）"

[packages-v2]
"openssl" = "< 3.6.3"
"openssl+32" = "< 3.6.3"
