security = true
must_match_all = false

[name]
default = "OpenSSL 3.5.4"

[caution]
default = "Fixes 3 security vulnerabilities disclosed in OpenSSL Security Advisory on September 30th, 2025 (Severity: Moderate)"
zh_CN = "修复 OpenSSL 在 2025 年 9 月 30 日发布的安全公告中披露的 3 个安全漏洞（严重性：中）"

[packages-v2]
"openssl" = "< 3.5.4"
"openssl+32" = "< 3.5.4"
