security = true

[name]
default = "OpenVPN 2.7.5"

[caution]
default = "Fixes a Reachable Assertion vulnerability (CVE-2026-13122, Severity: Medium) and a Missing Release of Memory after Effective Lifetime vulnerability (CVE-2026-13698, Severity: High)"
zh_CN = "修复 1 个可达断言漏洞（漏洞编号 CVE-2026-13122，严重性：中）和 1 个内存有效生命周期后未释放漏洞（漏洞编号 CVE-2026-13698，严重性：高）"

[packages-v2]
"openvpn" = "< 2.7.5"
