security = true
must_match_all = false

[name]
default = "OpenSSL 3.6.1"

[caution]
default = "Fixes 12 security vulnerabilities disclosed in OpenSSL Security Advisory on January 27, 2026 (1 of high severity)"
zh_CN = "修复 OpenSSL 在 2026 年 1 月 27 日发布的安全公告中披露的 21 个安全漏洞（含 1 个高危漏洞）"

[packages-v2]
"openssl" = "< 3.6.1"
"openssl+32" = "< 3.6.1"
