security = true

[name]
default = "OpenSSH 10.3p1"

[caution]
default = "Fixes 5 security vulnerabilities (including one vulnerability with High severity)"
zh_CN = "修复 5 项安全漏洞（其中高危漏洞一项）"

[packages-v2]
"openssh" = "< 10.3p1"
