security = true

[name]
default = "OpenJPEG 2.5.4"

[caution]
default = "Fixes an Out-of-Bounds Heap Memory Write vulnerability (CVE-2025-54874, Severity: High) and 2 Heap-based Buffer Overflow vulnerabilities (CVE-2024-56826 and CVE-2024-56827, Severity: Medium)"
zh_CN = "修复 1 个越界堆内存写入漏洞（CVE-2025-54874，严重性：高）和 2 个堆缓冲区溢出漏洞（CVE-2024-56826 和 CVE-2024-56827，严重性：中）"

[packages-v2]
"openjpeg" = "< 2.5.4"
