security = true

[name]
default = "OpenJFX 17.0.20"

[caution]
default = "Fixes 10 security vulnerabilities not yet publicly disclosed"
zh_CN = "修复 10 个暂未公开的安全漏洞"

[packages-v2]
openjfx-17 = "< 17.0.20+3"
