security = true
must_match_all = false

[name]
default = "OpenSSL 1.1.1zg"

[caution]
default = "Fixes 4 security vulnerabilities disclosed in OpenSSL Security Advisory on April 7, 2026"
zh_CN = "修复 OpenSSL 在 2026 年 4 月 7 日发布的安全公告中披露的 4 个安全漏洞"

[packages-v2]
"openssl-1.1" = "< 1.1.1zg"
"openssl-1.1+32" = "< 1.1.1zg"
