security = true

[name]
default = "PackageKit 1.3.5"

[caution]
default = "Fixes a TOCTOU (Time-Of-Check to Time-of-Use) race condition vulnerability - CVE-2026-41651 (severity: High)"
zh_CN = "修复一个 TOCTOU（检查到使用时间）竞态条件漏洞，漏洞编号 CVE-2026-41651（严重性：高）"

[packages-v2]
"packagekit" = "< 1.3.5"
