security = true

[name]
default = "Perl XML::Parser 2.51"

[caution]
default = "Fixes a Heap-based Buffer Overflow and Improper Handling of Unicode Encoding vulnerability - CVE-2006-10002 (Severity: Critical)"
zh_CN = "修复一个堆缓冲区溢出 (Heap-based Buffer Overflow) 及 Unicode 编码处理不当漏洞，漏洞编号 CVE-2006-10002（严重性：严重）"

[packages-v2]
"perl-xml-parser" = "< 2.51"
