security = true

[name]
default = "Perl Image::ExifTool 13.52"

[caution]
default = "Fixes an OS command injection vulnerability - CVE-2026-3102 (Severity: High)"
zh_CN = "修复一个操作系统命令注入漏洞，漏洞编号 CVE-2026-3102（严重性：高）"

[packages-v2]
"perl-image-exiftool" = "< 13.52"
