security = true

[name]
default = "Perl JSON::XS 4.04"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability - CVE-2025-40928 (Severity: High)"
zh_CN = "修复一处堆缓冲区溢出 (Heap-based Buffer Overflow) 漏洞，漏洞编号 CVE-2025-40928（严重性：高）"

[packages]
"perl-json-xs" = "4.04"
