security = true

[name]
default = "Perl DBI 1.654"

[caution]
default = "Fixes 12 security vulnerabilities (including 7 of Critical and 3 of High severity)"
zh_CN = "修复 12 个安全漏洞（含 7 个严重漏洞和 3 个高危漏洞）"

[packages-v2]
"perl-dbi" = "< 1.654"
