security = true

[name]
default = "PHP 8.5.8"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability (CVE-2026-14355, Severity: Medium)"
zh_CN = "修复 1 个堆缓冲区溢出漏洞（漏洞编号 CVE-2026-14355，严重性：中）"

[packages-v2]
"php" = "< 1:8.5.8"
