security = true

[name]
default = "PHP 8.5.9"

[caution]
default = "Fixes 4 security vulnerabilities (including 2 of high severity and 1 of medium severity)"
zh_CN = "修复 4 个安全漏洞（含 2 个高危漏洞和 1 个中危漏洞）"

[packages-v2]
"php" = "< 1:8.5.9"
