security = true

[name]
default = "PHP 8.5.6"

[caution]
default = "Fixes 10 security vulnerabilities disclosed since PHP 8.5.6 (3 of High, 5 of Medium, and 2 of Low severity)"
zh_CN = "修复自 PHP 8.5.6 起披露的 10 个安全漏洞（含 3 个高危、5 个中危及 2 个低危漏洞）"

[packages-v2]
"php" = "< 1:8.5.6"
