security = true

[name]
default = "PHP 8.5.1"

[caution]
default = "Fixes 10 security vulnerabilities since PHP 8.4.7 (8 of moderate severity, 2 of low severity)"
zh_CN = "修复自 PHP 8.4.7 起的 10 个安全漏洞（8 个中危漏洞，2 个低危漏洞）"

[packages-v2]
"php" = "< 1:8.5.1"
