security = true

[name]
default = "pip 26.1.2"

[caution]
default = "Fixes a Improper Limitation of a Pathname to a Restricted Directory (Path Traversal) vulnerability (CVE-2026-8643, Severity: Medium)"
zh_CN = "修复一个对路径名的限制不恰当（路径遍历）漏洞（漏洞编号 CVE-2026-8643，严重性：中）"

[packages-v2]
"pip" = "< 26.1.2"
