security = true

[name]
default = "pip 26.0.1"

[caution]
default = "Fixes a Interpretation Conflict, Misinterpretation of Input, or Unrestricted Upload of File with Dangerous Type vulnerability - CVE-2026-3219 (severity: Medium)"
zh_CN = "修复一个解释冲突、错误解析输入或危险类型文件的不加限制上传漏洞，漏洞编号 CVE-2026-3219（严重性：中）"

[packages-v2]
"pip" = "< 26.0.1"
