security = true

[name]
default = "Podman 5.8.2"

[caution]
default = "Fixes an OS Command Injection vulnerability (CVE-2026-33414, Severity: High)"
zh_CN = "修复一个系统命令注入漏洞（漏洞编号 CVE-2026-33414，严重性：高）"

[packages-v2]
"podman" = "< 5.8.2+vsock0.8.8"
