security = true

[name]
default = "podofo 1.1.1"

[caution]
default = "Fixes an Use After Free vulnerability (CVE-2025-46205, Severity: High)"
zh_CN = "修复一个释放后使用漏洞（CVE-2025-46205，严重性：高）"

[packages-v2]
"podofo" = "< 1.1.2"
