security = true

[name]
default = "Poppler 25.07.0 Security Update"
zh_CN = "Poppler 25.07.0 安全更新"
zh_TW = "Poppler 25.07.0 安全更新"

[caution]
default = "Fixes a remote Denial-of-Service vulnerability - CVE-2023-34872 (Severity: Medium)"
zh_CN = "修复一处远程拒绝服务攻击漏洞 - CVE-2023-34872（严重性：中）"
zh_TW = "修復一處遠端阻斷服務攻擊漏洞 - CVE-2023-34872（嚴重性：中）"

[packages]
"poppler" = "25.07.0"
