security = true

[name]
default = "PostgreSQL 18.3"

[caution]
default = "Fixes 7 security vulnerabilities (4 of high severity)"
zh_CN = "修复 7 个安全漏洞（含 4 个高危漏洞）"

[packages-v2]
"postgresql-18" = "< 18.3"
