security = true

[name]
default = "PostgreSQL 13.23"

[caution]
default = "Fixes an authentication vulnerability on CREATE STATISTICS command (CVE-2025-12817) , an integer wraparound vulnerability on libpq client library (CVE-2025-12818, moderate severity)"
zh_CN = "修复 CREATE STATISTICS 语句缺乏鉴权的漏洞 (CVE-2025-12817) 及 libpq 客户端库中的一处整数回绕漏洞 (CVE-2025-12818, 中严重性)"

[packages-v2]
"postgresql-13" = "< 13.23"
