security = true

[name]
default = "PostgreSQL 13.22"

[caution]
default = "Fixes 3 security vulnerabilities (2 of high severity)"
zh_CN = "修复 3 个安全漏洞（含 2 个高危漏洞）"

[packages-v2]
"postgresql-13" = "< 13.22"
