security = true
must_match_all = false

[name]
default = "PostgreSQL Security Update: Version 14.24/15.19/16.15/17.11/18.6"
zh_CN = "PostgreSQL 安全更新：版本 14.24/15.19/16.15/17.11/18.6"

[caution]
default = "Fixes 28 security vulnerabilities (including 18 of high severity and 7 of medium severity)"
zh_CN = "修复了 28 个安全漏洞（包括 18 个高危漏洞和 7 个中危漏洞）"

[packages-v2]
"postgresql-14" = "< 14.24"
"postgresql-15" = "< 15.19"
"postgresql-16" = "< 16.15"
"postgresql-17" = "< 17.11"
"postgresql-18" = "< 18.6"
