security = true
must_match_all = false

[name]
default = "PostgreSQL Security Update: Version 18.4, 17.10, 16.14, 15.18 and 14.23"
zh_CN = "PostgreSQL 安全更新：版本 18.4, 17.10, 16.14, 15.18 及 14.23"

[caution]
default = "Fixes 11 security vulnerabilities, including 3 SQL injection vulnerabilities (severity: High), one local file overwriting vulnerability (severity: High), one memory overiting vulnerability (severity: High), one arrary out of bounds vulnerability, and 5 medium and low severity vulnerabilities"
zh_CN = "修复了 11 个安全漏洞，其中包括三个 SQL 注入漏洞（严重性：高）、一个本地文件覆盖漏洞（严重性：高）、一个内存覆写漏洞（严重性：高）、一个数组索引越界漏洞（严重性：高）以及 5 个中低严重性安全漏洞"

[packages-v2]
"postgresql-14" = "< 14.23"
"postgresql-15" = "< 15.18"
"postgresql-16" = "< 16.14"
"postgresql-17" = "< 17.10"
"postgresql-18" = "< 18.4"
