security = true

[name]
default = "PostgreSQL 16.13"

[caution]
default = "Fixes 6 security vulnerabilities (3 of high severity)"
zh_CN = "修复 6 个安全漏洞（含 3 个高危漏洞）"

[packages-v2]
"postgresql-16" = "< 16.13"
