security = true

[name]
default = "Prism Launcher 11.1.1"

[caution]
default = "Fixes a Path Traversal vulnerability"
zh_CN = "修复 1 个路径遍历漏洞"
zh_TW = "修復 1 個路徑遍歷漏洞"

[packages-v2]
"prismlauncher" = "< 11.1.1"
