security = true

[name]
default = "Protocol Buffers 35.1"

[caution]
default = "Fixes an Uncontrolled Recursion vulnerability (CVE-2026-0994, Severity: High)"
zh_CN = "修复 1 个递归不受控漏洞（漏洞编号 CVE-2026-0994，严重性：高）"

[packages-v2]
"protobuf" = "< 35.1"
