security = true
must_match_all = false

[name]
default = "PuTTY 0.84"

[caution]
default = "Fixes 4 security vulnerabilities (1 of Medium severity)"
zh_CN = "修复 4 个安全漏洞（含 1 个中危漏洞）"

[packages-v2]
"putty" = "< 0.84"
