security = true

[name]
default = "Pytest 9.1.1"

[caution]
default = "Fixes a Creation of Temporary File in Directory with Insecure Permissions vulnerability (CVE-2025-71176, Severity: Moderate)"
zh_CN = "修复 1 个以不安全的权限创建临时文件漏洞（漏洞编号 CVE-2025-71176，严重性：中）"

[packages-v2]
"pytest" = "< 9.0.3"
