security = true

[name]
default = "Python 3.14.5"

[caution]
default = "Fixes a Path Traversal vulnerability (CVE-2026-7774, Severity: Medium)"
zh_CN = "修复一个路径穿越漏洞（漏洞编号 CVE-2026-7774，严重性：中）"

[packages-v2]
"python-3" = "< 3.14.5"
