security = true

[name]
default = "Python 3.14.7"

[caution]
default = "Fixes a Cleartext Transmission of Sensitive Information vulnerability (CVE-2026-15806, Severity: Medium) and a Interpretation Conflict vulnerability (CVE-2026-17084, Severity: Medium)"
zh_CN = "修复 1 个明文传输敏感信息漏洞（漏洞编号 CVE-2026-15806，严重性：中）和 1 个解释冲突漏洞（漏洞编号 CVE-2026-17084，严重性：中）"

[packages-v2]
"python-3" = "< 3.14.7"
