security = true

[name]
default = "Python 3.14.5, Revision 1"
zh_CN = "Python 3.14.5，修订版本 1"

[caution]
default = "Fixes a Stack-based Buffer Overflow vulnerability (CVE-2026-9669, Severity: High)"
zh_CN = "修复 1 个栈缓冲区溢出漏洞（漏洞编号 CVE-2026-9669，严重性：高）"

[packages-v2]
"python-3" = "< 3.14.5-1"
