security = true

[name]
default = "Python 3.14.7, Revision 2"
zh_CN = "Python 3.14.7，修订版本 2"

[caution]
default = "Fixes an Improper Validation of Certificate with Host Mismatch vulnerability (CVE-2026-19553, Severity: High) and an Use After Free vulnerability (CVE-2026-19445, Severity: Critical)"
zh_CN = "修复 1 个证书主机名不匹配时验证不当漏洞（漏洞编号 CVE-2026-19553，严重性：高）和 1 个使用后释放漏洞（漏洞编号 CVE-2026-19445，严重性：严重）"

[packages-v2]
"python-3" = "< 3.14.7-2"
