security = false

[name]
default = "Python 3.14.0 Release Candidate 2"
zh_CN = "Python 3.14.0 发行候选 2"

[caution]
default = "Updates Python 3 to 3.14.0 Release Candidate 2"
zh_CN = "更新 Python 3 至 3.14.0 发行候选 2"

[packages]
"python-3" = "3.14.0~rc2"
