security = true

[name]
default = "Python 3.14.6, Revision 1"
zh_CN = "Python 3.14.6，修订版本 1"

[caution]
default = "Fixes a Uncontrolled Resource Consumption vulnerability (CVE-2026-15308, Severity: High)"
zh_CN = "修复 1 个资源消耗不受控漏洞（漏洞编号 CVE-2026-15308，严重性：高）"

[packages-v2]
"python-3" = "< 3.14.6-1"
