security = true

[name]
default = "radare2 6.0.7"

[caution]
default = "Fixes 10 security vulnerabilities (2 of critical severity, 1 of high severity)"
zh_CN = "修复 10 个安全漏洞（含 2 个严重漏洞和 1 个高危漏洞）"

[packages-v2]
"radare2" = "<6.0.7"
