security = true

[name]
default = "Rclone 1.74.4"

[caution]
default = "Fixes 4 security vulnerabilities (including 1 of critical severity, 2 of high severity, and 1 of medium severity)"
zh_CN = "修复 4 个安全漏洞（含 1 个严重漏洞、2 个高危漏洞和 1 个中危漏洞）"

[packages-v2]
"rclone" = "< 1.74.4"
