security = true

[name]
default = "Rclone 1.74.0"

[caution]
default = "Fixes 2 Missing Authentication for Critical Function vulnerability (CVE-2026-41176, CVE-2026-41179, Severity: Critical)"
zh_CN = "修复了两个关键功能缺少认证的漏洞（CVE-2026-41176、CVE-2026-41179，严重性：严重）"

[packages-v2]
"rclone" = "< 1.74.0"
