security = true

[name]
default = "requests 2.34.2"

[caution]
default = "Fixes an Insecure Temporary File vulnerability (CVE-2026-25645, Severity: Medium)"
zh_CN = "修复一个不安全的临时文件漏洞（CVE-2026-25645，严重性：中）"

[packages-v2]
"requests" = "< 2.34.2"
