security = true

[name]
default = "rsync 3.5.0"

[caution]
default = "Fixes 33 security vulnerabilities (including 1 of critical severity, 17 of high severity, and 15 of medium severity)"
zh_CN = "修复 33 个安全漏洞（含 1 个严重漏洞、17 个高危漏洞和 15 个中危漏洞）"

[packages-v2]
"rsync" = "< 3.5.0"
