security = true

[name]
default = "runc 1.5.0"

[caution]
default = "Fixes a Symlink Following following vulnerability (CVE-2026-41579, Severity: Low)"
zh_CN = "修复 1 个符号链接跟随漏洞（漏洞编号 CVE-2026-41579，严重性：低）"

[packages-v2]
"runc" = "< 1.5.0"
