security = true

[name]
default = "SAMtools 1.23.1"

[caution]
default = "Fixes a NULL Pointer Dereference - CVE-2026-31973 (severity: Moderate)"
zh_CN = "修复一个空指针解引用，漏洞编号 CVE-2026-31973（严重性：中）"

[packages-v2]
samtools = "< 1.23.1"
