security = true
must_match_all = false

[name]
default = "SQLite 3.53.3"

[caution]
default = "Fixes 2 Heap-Based Buffer Overflow vulnerability (CVE-2026-11822, CVE-2026-11824, Severity: High)"
zh_CN = "修复 2 个基于堆的缓冲区溢出漏洞（漏洞编号 CVE-2026-11822 和 CVE-2026-11824，严重性：高）"

[packages-v2]
"sqlite" = "< 3.53.3"
"sqlite+32" = "< 3.53.3"
