security = true

[name]
default = "Squid 7.5"

[caution]
default = "Fixes an Improper Resource Locking vulnerability (CVE-2026-32748, Severity: High), an Out-of-bounds Read vulnerability (CVE-2026-33515, Severity: Medium), and an Use After Free vulnerability (CVE-2026-33526, Severity: High)"
zh_CN = "修复了一个资源加锁不恰当漏洞（CVE-2026-32748，严重性：高）、一个越界读取漏洞（CVE-2026-33515，严重性：中），以及一个释放后使用漏洞（CVE-2026-33526，严重性：高）"

[packages-v2]
"squid" = "< 7.5"
