security = true

[name]
default = "sudo 1.9.17p1"

[caution]
default = "Fixes two local-privilege-escalation vulnerabilities - CVE-2025-32462 and CVE-2025-32463 (Severity: High)"
zh_CN = "修复两处本地提权 (local-privilege-escalation) 漏洞，漏洞编号 CVE-2025-32462 和 CVE-2025-32463（严重性：高）"

[packages]
"sudo" = "1.9.17p1"
