security = false

[name]
default = "systemd default SysRq config update"
zh_CN = "systemd SysRq 默认设置更新"

[caution]
default = "Enabled all except debugging dump Magic SysRq keys by default"
zh_CN = "默认启用除调试转储以外的所有 SysRq 组合键"

[packages]
systemd = "1:257.6-1"
