security = true

[name]
default = "systemd 257.6"
zh_CN = "systemd 257.6"

[caution]
default = "Fixes a local privilege escalation vulnerability - CVE-2025-4598 (Severity: High)"
zh_CN = "修复一处本地提权漏洞，漏洞编号 CVE-2025-4598（严重性：高）"

[packages]
systemd = "1:257.6"
