security = true

[name]
default = "Telegram Desktop 7.2.9"

[caution]
default = "Fixes an Improper Neutralization of Record Delimiters vulnerability (CVE-2026-107181, Severity: High)"
zh_CN = "修复 1 个未正确处理记录分隔符漏洞（CVE-2026-107181，严重性：高）"
zh_TW = "修復 1 個未正確處理記錄分隔值漏洞（CVE-2026-107181，嚴重性：高）"

[packages-v2]
"telegram-desktop" = "< 7.2.9"
