security = true

[name]
default = "Thunderbird 148.0"

[caution]
default = "Fixes 50 security vulnerability disclosed in Mozilla Foundation Security Advisory 2026-16 (30 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2026-16 号安全公告中披露的 50 个安全漏洞（含 30 个高危漏洞）"

[packages-v2]
thunderbird = "< 148.0"
