security = true

[name]
default = "Thunderbird 137.0"

[caution]
default = "Fixes 7 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-23 (3 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-23 号安全公告中披露的 7 个安全漏洞（含 3 个高危漏洞）"

[packages]
thunderbird = "137.0.1"
