security = true

[name]
default = "Thunderbird 137.0.2"

[caution]
default = "Fixes 3 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-26 (2 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-26 号安全公告中披露的 3 个安全漏洞（含 2 个高危漏洞）"

[packages]
thunderbird = "137.0.2"
