security = true

[name]
default = "Thunderbird 155.0"

[caution]
default = "Fixes 30 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2026-86 (13 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2026-86 号安全公告中披露的 30 个安全漏洞（含 13 个高危漏洞）"

[packages-v2]
thunderbird = "< 155.0"
