security = true

[name]
default = "Thunderbird 151.0"

[caution]
default = "Fixes 29 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2026-50 (5 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2026-50 号安全公告中披露的 29 个安全漏洞（含 5 个高危漏洞）"

[packages-v2]
thunderbird = "< 151.0"
