security = true

[name]
default = "Thunderbird 139.0"

[caution]
default = "Fixes 10 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-45 (1 of critical severity)"
zh_CN = "修复 Mozilla 基金会第 2025-45 号安全公告中披露的 10 个安全漏洞（含 1 个严重漏洞）"

[packages]
thunderbird = "139.0"
