security = true

[name]
default = "Thunderbird 142.0"

[caution]
default = "Fixes 6 security vulnerabilities disclosed in Mozilla Foundation Security Advisory 2025-70 (5 of high severity)"
zh_CN = "修复 Mozilla 基金会第 2025-70 号安全公告中披露的 6 个安全漏洞（含 5 个高危漏洞）"

[packages]
thunderbird = "142.0"
