security = true

[name]
default = "TigerVNC 1.16.2"

[caution]
default = "Fixes a Denial-of-Service vulnerability - CVE-2026-34352 (Severity: High)"
zh_CN = "修复一个拒绝服务漏洞，漏洞编号 CVE-2026-34352（严重性：高）"

[packages-v2]
"tigervnc" = "< 1.16.2+xserver21.1.21"
