security = true

[name]
default = "TigerVNC builtin X.Org Server Update"
zh_CN = "TigerVNC 内建 X.Org Server 更新"

[caution]
default = "Fixes 6 security vulnerabilities disclosed in X.Org's Security Advisory on June 17, 2025"
zh_CN = "修复 X.Org 在 2025 年 6 月 17 日的安全公告中披露的 6 个安全漏洞"

[packages]
"tigervnc" = "1.15.0+xserver21.1.17"
