security = true

[name]
default = "Tornado 6.5.5"

[caution]
default = "Fixes an Uncontrolled Resource Consumption vulnerability (CVE-2026-31958, Severity: High) and an Improper Handling of Invalid Use of Special Elements vulnerability (CVE-2026-35536, Severity: High)"
zh_CN = "修复一个未加控制的资源消耗漏洞（漏洞编号 CVE-2026-31958，严重性：高）和一个特殊元素净化处理不恰当漏洞（漏洞编号 CVE-2026-35536，严重性：高）"

[packages-v2]
"tornado" = "< 6.5.5"
