security = false

[name]
default = "Time Zone Database 2026c"
zh_CN = "时区信息数据库 2026c"
zh_TW = "時區資訊資料庫 2026c"

[caution]
default = "Includes time zone changes for Alberta, Canada to move to permanent daylight saving time, effective November 1, 2026 and, for Morocco, to move from UTC+1 to UTC, effective September 20, 2026"
zh_CN = "包含加拿大阿尔伯塔省自 2026 年 11 月 1 日起取消冬令时及摩洛哥自 2026 年 9 月 20 日起从 UTC+1 变更为 UTC 时区的更新"
zh_TW = "包含加拿大亞伯達省自 2026 年 11 月 1 日起取消冬令時及摩洛哥自 2026 年 9 月 20 日起从 UTC+1 變更為 UTC 時區的更新"

[packages-v2]
"tzdata" = "< 2026c"
