security = true

[name]
default = "U-Boot Utilities 2025.04"
zh_CN = "U-Boot 实用工具 2025.04"

[caution]
default = "Fixes multiple security vulnerabilities (5 of high severity, 1 low)"
zh_CN = "修复多个安全漏洞（含 5 个高危漏洞，1 个低危漏洞）"

[packages]
uboot-tools = "2025.04"
