security = true

[name]
default = "UDisks 2.11.2"

[caution]
default = "Fixes a Local Privilege Escalation vulnerability, codenamed \"disk2root\" (CVE-2026-7867, severity: High)"
zh_CN = "修复代号为 \"disk2root\" 的本地提权漏洞（CVE-2026-7867，严重性：高）"

[packages-v2]
"udisks-2" = "< 2.11.2"
