security = true

[name]
default = "UDisks 2.10.2"

[caution]
default = "Fixes an out-of-bounds read vulnerability - CVE-2025-8067 (Severity: High)"
zh_CN = "修复一处越界读取 (out-of-bounds read) 漏洞，漏洞编号 CVE-2025-8067（严重性：高）"

[packages]
"udisks-2" = "2.10.2"
