security = true

[name]
default = "UltraJSON 5.13.0"

[caution]
default = "Fixes an Improper Input Validation vulnerability (CVE-2026-54911, Severity: Moderate)"
zh_CN = "修复 1 个输入验证不恰当漏洞（漏洞编号 CVE-2026-54911，严重性：中）"

[packages-v2]
"ujson" = "< 5.13.0"
