security = true

[name]
default = "Unbound 1.26.1"

[caution]
default = "Fixes 9 security vulnerabilities (including 1 of critical severity, 2 of high severity, 5 of medium severity and 1 of low severity)"
zh_CN = "修复 9 个安全漏洞（含 1 个严重漏洞、2 个高危漏洞、5 个中危漏洞和 1 个低危漏洞）"

[packages-v2]
"unbound" = "< 1.26.1+icannbundle20260528"
