security = true

[name]
default = "Unbound 1.24.2"

[caution]
default = "Fixes a possible domain hijack vulnerability - CVE-2025-11411 (severity: moderate)"
zh_CN = "修复一个潜在域名劫持漏洞，漏洞编号 CVE-2025-11411（严重性：中等）"

[packages-v2]
"unbound" = "< 1.24.2+icannbundle20210902"
