security = true

[name]
default = "Unbound 1.23.1+icannbundle20210902"

[caution]
default = "Fixes 3 security vulnerabilities (1 each of high, medium and low severities)"
zh_CN = "修复 3 个安全漏洞（高危、中危、低危各一个）"

[packages]
"unbound" = "1.23.1+icannbundle20210902"
