security = true

[name]
default = "uriparser 1.0.2"

[caution]
default = "Fixes a numeric truncation vulnerability (CVE-2026-44927, Severity: Low) and a Always-Incorrect Control Flow Implementation vulnerability (CVE-2026-44928, Severity: Low)"
zh_CN = "修复一个数值截断漏洞（CVE-2026-44927，严重性：低）和一个控制流实现错误漏洞（CVE-2026-44928，严重性：低）"

[packages-v2]
"uriparser" = "< 1.0.2"
