security = true

[name]
default = "uriparser 1.0.0 Security Update"
zh_CN = "uriparser 1.0.0 安全更新"

[caution]
default = "Fixes a Denial of Service (DoS) vulnerability - CVE-2025-67899 (Severity: Low)"
zh_CN = "修复一处拒绝服务 (Denial of Service, DoS) 漏洞，漏洞编号 CVE-2025-67899（严重性：低）"

[packages-v2]
"uriparser" = "< 1.0.0"
