security = true

[name]
default = "urllib3 2.7.0"

[caution]
default = "Fixes an Exposure of Sensitive Information to an Unauthorized Actor vulnerability (CVE-2026-44431, severity: Medium) and a Data Amplification vulnerability (CVE-2026-44432, severity: High) "
zh_CN = "修复一个向未鉴权角色暴露敏感信息的漏洞（CVE-2026-44431，严重性：中）和一个数据放大漏洞（CVE-2026-44432，严重性：高）"

[packages-v2]
"urllib3" = "< 2.7.0"
