security = true

[name]
default = "usbredir 0.15.0"

[caution]
default = "Fixes an Use After Free vulnerability (CVE-2021-3700, Severity: Medium)"
zh_CN = "修复一个释放后使用漏洞（CVE-2021-3700，严重性：中）"

[packages-v2]
"usbredir" = "< 0.15.0"
