security = true
must_match_all = false

[name]
default = "util-linux 2.42.3"

[caution]
default = "Fixes a Use After Free vulnerability (CVE-2026-13595, Severity: Medium)"
zh_CN = "修复 1 处释放后使用漏洞（CVE-2026-13595，严重性：中）"

[packages-v2]
"util-linux" = "< 2.42.3"
"util-linux+32" = "< 2.42.3"
