security = true

[name]
default = "util-linux 2.42"

[caution]
default = "Fixes a TOCTOU (Time-Of-Check to Time-of-Use) race condition vulnerability - CVE-2026-27456 (severity: Medium)"
zh_CN = "修复一处 TOCTOU（检查到使用时间）竞态条件漏洞，漏洞编号 CVE-2026-27456（严重性：中）"

[packages-v2]
"util-linux" = "< 2.42"
