security = true

[name]
default = "uv 0.8.6"

[caution]
default = "Fixes a vulnerability that enables malicious ZIP content to be extracted via package installers due to parsing differentials - CVE-2025-54368 (Severity: Medium)"
zh_CN = "修复一处利用解析实现差异导致某些组件包安装器解压有害 ZIP 内容的漏洞，漏洞编号 CVE-2025-54368（严重性：中）"

[packages]
"uv" = "0.8.6"
