security = true

[name]
default = "Vim 9.2.0277"

[caution]
default = "Fixes a remote code execution vulnerability (CVE-2026-34982, Severity: High)"
zh_CN = "修复一个远程代码执行漏洞（漏洞编号 CVE-2026-34982，严重性：高）"

[packages-v2]
"vim" = "< 9.2.0277"
