security = true

[name]
default = "Vim 9.2.0280"

[caution]
default = "Fixes a Improper Limitation of a Pathname to a Restricted Directory (Path Traversal) vulnerability (Severity: Low)"
zh_CN = "修复一个对路径名的限制不恰当（路径遍历）漏洞（严重性：低）"

[packages-v2]
"vim" = "< 9.2.0280"
