security = true

[name]
default = "Vim 9.2.0653"

[caution]
default = "Fixes an Out-of-bounds Write vulnerability (Severity: Moderate)"
zh_CN = "修复 1 个越界写溢出漏洞（严重性：中）"

[packages-v2]
"vim" = "< 9.2.0653"
