security = true

[name]
default = "Vim 9.2.0437"

[caution]
default = "Fixes a OS Command Injection vulnerability (Severity: Medium)"
zh_CN = "修复一个系统命令注入漏洞（严重性：中）"

[packages-v2]
"vim" = "< 9.2.0437"
