security = true

[name]
default = "Vim 9.2.0272"

[caution]
default = "Fixes an arbitrary OS command execution vulnerability (severity: High)"
zh_CN = "修复一个任意操作系统命令执行 (Arbitrary OS Command Execution) 漏洞（严重性：高）"

[packages-v2]
"vim" = "< 9.2.0272"
