security = true

[name]
default = "Vim 9.2.0680"

[caution]
default = "Fixes an Out-of-bounds Read vulnerability (Severity: Moderate)"
zh_CN = "修复 1 个越界读取漏洞（严重性：中）"

[packages-v2]
"vim" = ">= 9.2.0320 && < 9.2.0680"
