security = true

[name]
default = "Vim 9.2.0586"

[caution]
default = "Fixes 2 Out-of-bounds Read vulnerability (Severity: Moderate) and a Code Injection vulnerability (Severity: Moderate)"
zh_CN = "修复 2 个越界读溢出漏洞（严重性：中）和 1 个代码注入漏洞（严重性：中）"

[packages-v2]
"vim" = "< 9.2.0586"
