security = true

[name]
default = "Vim 9.2.1014"

[caution]
default = "Fixes an Out-of-bounds Write vulnerability (Severity: Moderate) and an Incorrect Calculation of Buffer Size vulnerability (Severity: Low)"
zh_CN = "修复 1 个越界写入漏洞（严重性：中）和 1 个缓冲区大小计算错误漏洞（严重性：低）"

[packages-v2]
"vim" = "< 9.2.1014"
