security = true

[name]
default = "Vim 9.2.0209"

[caution]
default = "Fixes a OS Command Injection vulnerability - CVE-2026-33412 (severity: Medium)"
zh_CN = "修复一个操作系统命令注入 (OS Command Injection) 漏洞，漏洞编号 CVE-2026-33412（严重性：中）"

[packages-v2]
"vim" = "< 9.2.0209"
