security = true

[name]
default = "Vim 9.2.1091"

[caution]
default = "Fixes an Improper Neutralization of Argument Delimiters in a Command (Argument Injection) and Improper Control of Generation of Code (Code Injection) vulnerability (Severity: Low)"
zh_CN = "修复 1 个命令参数分隔符处理不当（参数注入）及代码生成控制不当（代码注入）漏洞（严重性：低）"
zh_TW = "修復 1 個指令引數分隔符號處理不當（引數注入）及程式碼生成控制不當（程式碼注入）漏洞（嚴重性：低）"

[packages-v2]
"vim" = "< 9.2.1090"
