security = true

[name]
default = "Oracle VM VirtualBox 7.1.8"

[caution]
default = "Fixes 3 security vulnerabilities disclosed in Oracle Critical Patch Update Advisory - April 2025 (1 of high severity)"
zh_CN = "修复 Oracle 重要更新公告（2025 年 4 月）中披露的 3 个安装漏洞（含 1 个高危漏洞）"

[packages]
"virtualbox" = "7.1.8"
