security = true

[name]
default = "Oracle VM VirtualBox 7.2.18"

[caution]
default = "Fixes 15 security vulnerabilities disclosed in Oracle Critical Security Patch Update Advisory - September 2026 (4 of High, and 9 of Medium severity)"
zh_CN = "修复 Oracle 重要安全更新公告（2026 年 9 月）中披露的 15 个安全漏洞（含 4 个高危漏洞和 9 个中危漏洞）"

[packages-v2]
"virtualbox" = ">= 7.2.16 && < 7.2.18"
