security = true

[name]
default = "Oracle VM VirtualBox 7.2.14"

[caution]
default = "Fixes 15 security vulnerabilities disclosed in Oracle Critical Patch Update Advisory - July 2026 (5 of High, and 7 of Medium severity)"
zh_CN = "修复 Oracle 重要更新公告（2026 年 7 月）中披露的 15 个安全漏洞（含 5 个高危漏洞和 7 个中危漏洞）"

[packages-v2]
"virtualbox" = ">= 7.2.12 && < 7.2.14"
