security = true

[name]
default = "w3m 0.5.6"

[caution]
default = "Fixes 2 Out-of-Bounds Read vulnerability (CVE-2023-38252 and CVE-2023-38253, Severity: Medium)"
zh_CN = "修复 2 个越界读取漏洞（漏洞编号 CVE-2023-38252、CVE-2023-38253，严重性：中）"

[packages-v2]
"w3m" = "< 0.5.6"
