security = true

[name]
default = "WebKitGTK 2.54.0"

[caution]
default = "Fixes 232 security vulnerabilities disclosed in WebKitGTK and WPE WebKit Security Advisories"
zh_CN = "修复 WebKitGTK 及 WPE WebKit 第 WSA-2026-0006 号安全公告中披露的 232 个安全漏洞"

[packages-v2]
"webkit2gtk" = "< 1:2.54.0"
