security = true

[name]
default = "WebKitGTK 2.48.3"

[caution]
default = "Fixes 16 security vulnerabilities disclosed in WebKitGTK and WPE WebKit Security Advisories WSA-2025-0002, WSA-2025-0003, and WSA-2025-0004 (2 of critical, 6 of high severity)"
zh_CN = "修复 WebKitGTK 及 WPE WebKit 第 WSA-2025-0002、WSA-2025-0003 及 WSA-2025-0004 号安全公告中披露的 16 个安全漏洞（含 2 个严重、6 个高危漏洞）"

[packages]
"webkit2gtk" = "1:2.48.3"
