security = true

[name]
default = "WebKitGTK 2.48.6"

[caution]
default = "Fixes 10 security vulnerabilities disclosed in WebKitGTK and WPE WebKit Security Advisories WSA-2025-0005"
zh_CN = "修复 WebKitGTK 及 WPE WebKit 第 WSA-2025-0005 号安全公告中披露的 10 个安全漏洞"

[packages]
"webkit2gtk" = "1:2.48.6"
