security = true

[name]
default = "WebKitGTK 2.50.3"

[caution]
default = "Fixes 5 security vulnerabilities disclosed in WebKitGTK and WPE WebKit Security Advisories WSA-2025-0009 (Severity: High)"
zh_CN = "修复 WebKitGTK 及 WPE WebKit 第 WSA-2025-0009 号安全公告中披露的 5 个安全漏洞（严重性：高）"

[packages-v2]
"webkit2gtk" = "< 1:2.50.3"
