security = true

[name]
default = "WebKitGTK 2.50.0"

[caution]
default = "Fixes 4 security vulnerabilities disclosed in WebKitGTK and WPE WebKit Security Advisories WSA-2025-0006 (Severity: Critical)"
zh_CN = "修复 WebKitGTK 及 WPE WebKit 第 WSA-2025-0006 号安全公告中披露的 4 个安全漏洞（严重性：严重）"

[packages-v2]
"webkit2gtk" = "< 1:2.50.0"
