security = true

[name]
default = "WebKitGTK 2.52.0"

[caution]
default = "Fixes 17 security vulnerabilities disclosed in WebKitGTK and WPE WebKit Security Advisories WSA-2026-0001 (including 4 of high severity, 13 of medium severity)"
zh_CN = "修复 WebKitGTK 及 WPE WebKit 第 WSA-2026-0001 号安全公告中披露的 17 个安全漏洞（含 4 个高危漏洞及 13 个中危漏洞）"

[packages-v2]
"webkit2gtk" = "< 1:2.52.0"
