security = true

[name]
default = "WeeChat 4.10.1"

[caution]
default = "Fixes 6 vulnerabilities disclosed in WeeChat Security Advisories on Sep 5, 2026 (including 1 of Critical, 3 of High, and 2 of Medium severity)"
zh_CN = "修复 WeeChat 安全公告在 2026 年 9 月 5 日披露的 6 个安全漏洞（含 1 个严重漏洞、3 个高危漏洞和 2 个中危漏洞）"
zh_TW = "修復 WeeChat 安全公告在 2026 年 9 月 5 日披露的 6 個安全漏洞（含 1 個嚴重漏洞、3 個高危漏洞和 2 個中危漏洞）"

[packages-v2]
"weechat" = "< 4.10.1"
