security = true

[name]
default = "Werkzeug 3.1.8"

[caution]
default = "Fixes 3 improper handling of device names vulnerabilities (CVE-2025-66221, CVE-2026-21860, and CVE-2026-27199, Severity: Medium)"
zh_CN = "修复 3 个设备名处理不当漏洞（CVE-2025-66221、CVE-2026-21860 和 CVE-2026-27199，严重性：中）"

[packages-v2]
"werkzeug" = "< 3.1.8"
