security = true

[name]
default = "Wireshark 4.6.2"

[caution]
default = "Fixes 2 Denial of Service (DoS) vulnerabilities (severity: medium)"
zh_CN = "修复 2 个的拒绝服务（DoS）漏洞（严重性：中等）"

[packages-v2]
"wireshark" = "< 4.6.2"
