security = true

[name]
default = "wolfSSL 5.9.1"

[caution]
default = "Fixes 38 security vulnerabilities (including 9 of Critical severity, 14 of High, and 13 of Medium severity)"
zh_CN = "修复 38 个安全漏洞（含 9 个严重漏洞、14 个高危漏洞和 13 个中危漏洞）"

[packages-v2]
"wolfssl" = "< 5.9.1"
