security = true

[name]
default = "wolfSSL 5.9.2"

[caution]
default = "Fixes 18 security vulnerabilities (including 6 of High, and 12 of Medium severity)"
zh_CN = "修复 18 个安全漏洞（含 6 个高危漏洞和 12 个中危漏洞）"

[packages-v2]
"wolfssl" = "< 5.9.2"
