security = true

[name]
default = "wolfSSL 5.8.4"

[caution]
default = "Fixes 5 security vulnerabilities (1 of critical severity, 1 high, 3 medium)"
zh_CN = "修复 5 个安全漏洞（含 1 个严重漏洞，1 个高危漏洞，3 个中危漏洞）"

[packages-v2]
"wolfssl" = "< 5.8.4"
