security = true

[name]
default = "XKB Keymap Compiler (xkbcomp) 1.5.0"
zh_CN = "XKB 键盘布局编译器 (xkbcomp) 1.5.0"

[caution]
default = "Fixes 4 security vulnerabilities in xkbcomp(1) (4 of moderate severity)"
zh_CN = "修复 xkbcomp(1) 中的 4 个安全漏洞（严重性：中）"

[packages-v2]
"x11-app" = "< 7.7.20251203"
