security = true

[name]
default = "x11vnc 0.9.17"

[caution]
default = "Fixes an Incorrect Permission Assignment for Critical Resource vulnerability (CVE-2020-29074, Severity: High)"
zh_CN = "修复一个关键资源权限分配错误漏洞（CVE-2020-29074，严重性：高）"

[packages-v2]
"x11vnc" = "< 0.9.17"
