security = true

[name]
default = "xerces-c 3.3.0"

[caution]
default = "Fixes a out-of-bounds read vulnerability (CVE-2023-37536, Severity: High) and a use-after-free vulnerability  (CVE-2024-23807, Severity: Critical)"
zh_CN = "修复一个越界读取漏洞 (CVE-2023-37536，严重性：高) 和一个释放后使用漏洞 (CVE-2024-23807，严重性：严重)"

[packages-v2]
"xerces-c" = "< 3.3.0"
