security = true
must_match_all = false

[name]
default = "X.Org Server 21.1.23"

[caution]
default = "Fixes 9 security vulnerabilities disclosed in X.Org's Security Advisory on June 2, 2026"
zh_CN = "修复 X.Org 在 2026 年 6 月 2 日的安全公告中披露的 9 个安全漏洞"

[packages-v2]
"tigervnc" = "< 1.16.2+xserver21.1.23"
"xorg-server" = "< 21.1.23"
