security = true
must_match_all = false

[name]
default = "X.Org Server 21.1.24 and Xwayland 24.1.13"
zh_CN = "X.Org Server 21.1.24 和 Xwayland 24.1.13"

[caution]
default = "Fixes a Heap-based Buffer Overflow vulnerability (CVE-2026-55999, Severity: High) and a Use After Free vulnerability (CVE-2026-56000, Severity: High)"
zh_CN = "修复 1 个基于堆的缓冲区溢出漏洞（漏洞编号 CVE-2026-55999，严重性：高）和 1 个释放后使用漏洞（漏洞编号 CVE-2026-56000，严重性：高）"

[packages-v2]
"xorg-server" = "< 21.1.24"
"xwayland" = "< 24.1.13"
