security = true

[name]
default = "X.Org Server 21.1.17"

[caution]
default = "Fixes 6 security vulnerabilities disclosed in X.Org's Security Advisory on June 17, 2025"
zh_CN = "修复 X.Org 在 2025 年 6 月 17 日的安全公告中披露的 6 个安全漏洞"

[packages]
"xorg-server" = "21.1.17"
