security = true

[name]
default = "xrdp 0.10.6"

[caution]
default = "Fixes 9 security vulnerabilities (including 4 of Critical, 3 of High, and 2 of Medium severity)"
zh_CN = "修复 9 个安全漏洞（含 4 个严重漏洞、3 个高危漏洞和 2 个中危漏洞）"

[packages-v2]
"xrdp" = "< 0.10.6"
