security = true

[name]
default = "Xwayland 24.1.12"

[caution]
default = "Fixes 9 security vulnerabilities disclosed in X.Org's Security Advisory on June 2, 2026"
zh_CN = "修复 X.Org 在 2026 年 6 月 2 日的安全公告中披露的 9 个安全漏洞"

[packages-v2]
"xwayland" = "< 24.1.12"
