security = true

[name]
default = "Xwayland 24.1.9"

[caution]
default = "Fixes 3 zero-day security vulnerabilities disclosed in X.Org's Security Advisory on October 28, 2025"
zh_CN = "修复 X.Org 在 2025 年 10 月 28 日的安全公告中披露的 3 个零日 (0-day) 安全漏洞"

[packages-v2]
"xwayland" = "< 24.1.9"
