security = true
must_match_all = false

[name]
default = "XZ 5.8.4"

[caution]
default = "Fixes an invalid memory access vulnerability in liblzma decoder functions - GHSA-5qpq-xqfv-j9pg (CVE pending)"
zh_CN = "修复 liblzma 解码器函数中一处无效内存访问漏洞，漏洞编号 GHSA-5qpq-xqfv-j9pg（CVE 编号待定）"

[packages-v2]
"xz" = "< 5.8.4"
"xz+32" = "< 5.8.4"
