security = true
must_match_all = false

[name]
default = "XZ 5.8.3"

[caution]
default = "Fixes a buffer overflow vulnerability - CVE-2026-34743"
zh_CN = "修复一个缓冲区溢出漏洞，漏洞编号 CVE-2026-34743"

[packages-v2]
"xz" = "< 5.8.3"
"xz+32" = "< 5.8.3"
