security = true

[name]
default = "XZ (liblzma) 5.8.1 Security Update"
zh_CN = "XZ (liblzma) 5.8.1 安全更新"

[caution]
default = "Fixes a use-after-free vulnerability - CVE-2025-31115 (Severity: High)"
zh_CN = "修复一处释放后使用 (use-after-free) 漏洞，漏洞编号 CVE-2025-31115（严重性：高）"

[packages]
xz = "5.8.1"
"xz+32" = "5.8.1"
