security = true

[name]
default = "Info-ZIP 3.0, Revision 7"
zh_CN = "Info-ZIP 3.0，修订版本 7"

[caution]
default = "Fixes a command injection vulnerability"
zh_CN = "修复一个命令注入漏洞"

[packages-v2]
"zip" = "< 3.0-7"
