exec-once = regreet; hyprctl dispatch exit
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_hyprland_qtutils_check = true
}

# Add the following code to /etc/greetd/config.toml
# [default_session]
# command = "Hyprland --config /etc/greetd/regreet-hyprland.conf"
# user = "greeter"
