#!/bin/bash

if [[ "${CROSS:-$ARCH}" != "amd64" ]]; then
    abinfo "Skipping the build of Carla Windows(R) plugin compatible layer..."
    abinfo "Installing binaries..."
    make install DESTDIR="${PKGDIR}/" PREFIX=/usr
else
    abinfo "Building extra Carla Windows(R) plugin compatible layer..."
    abdbg "Backing up current environment variables..."

    abdbg "Setting up environment variables for MinGW cross-compiling..."
    export CFLAGS="-ffat-lto-objects -fuse-linker-plugin -flto"
    export CXXFLAGS="-ffat-lto-objects -fuse-linker-plugin -flto"
    unset LDFLAGS
    export CC=/opt/w64/bin/x86_64-w64-mingw32-gcc
    export CXX=/opt/w64/bin/x86_64-w64-mingw32-g++
    export AR=/opt/w64/bin/x86_64-w64-mingw32-ar
    export PKG_CONFIG_PATH=/opt/w64/share
    export LDFLAGS="-static"
    export WIN32=true
    export WIN64=true

    abinfo "Building client-side Win64 loader..."
    make win64 HAVE_LIBLO=false -j$ABMK

    abinfo "Building client-side Win32 loader..."
    export CC=/opt/w64/bin/i686-w64-mingw32-gcc
    export CXX=/opt/w64/bin/i686-w64-mingw32-g++
    export AR=/opt/w64/bin/i686-w64-mingw32-ar
    make win32 HAVE_LIBLO=false -j$ABMK

    abdbg "Restoring environment variables..."
    unset CC
    unset CXX
    unset AR
    unset PKG_CONFIG_PATH
    unset LDFLAGS
    unset WIN32
    unset WIN64
    # winegcc is allergic to some of the flags
    export CFLAGS="-fno-lto"
    export CXXFLAGS="-fno-lto"

    abinfo "Building Wine loader stub (64 bit)..."
    make wine64
    abinfo "Building Wine loader stub (32 bit)..."
    make wine32

    abinfo "Installing binaries..."
    make install DESTDIR="${PKGDIR}/" PREFIX=/usr
fi
