#!/usr/bin/env bash
set -e

for i in ./autobuild/patches/*
do
  abinfo "Applying $i..."
  patch -Np1 -i "$i" || exit 1
done

abinfo "Installing PowerShell..."
mkdir .pwsh/
wget -O .pwsh/powershell-$PKGVER-linux-x64.tar.gz -- "https://github.com/PowerShell/PowerShell/releases/download/v$PKGVER/powershell-$PKGVER-linux-x64.tar.gz"
tar -xf .pwsh/powershell-$PKGVER-linux-x64.tar.gz -C .pwsh/

abinfo "Building PowerShell..."
./.pwsh/pwsh -c "& {Import-Module ./build.psm1; Start-PSBootstrap; Start-PSBuild -Output $PKGDIR/usr/lib/powershell -PSModuleRestore -Runtime linux-x64}"

mkdir -p "$PKGDIR/usr/bin"
ln -s "/usr/lib/powershell/pwsh" "$PKGDIR/usr/bin/pwsh"
