#!/usr/bin/env bash
set -e

export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

abinfo "Installing PowerShell..."
mkdir .pwsh
wget -O .pwsh/powershell-$PKGVER-linux-x64.tar.gz -- "https://github.com/PowerShell/PowerShell/releases/download/v$PKGVER/powershell-$PKGVER-linux-x64.tar.gz"
tar -xf .pwsh/powershell-$PKGVER-linux-x64.tar.gz -C .pwsh

abinfo "Building PowerShell..."
./.pwsh/pwsh -c "& {Import-Module ./build.psm1; Start-PSBootstrap; Start-PSBuild -Output $PKGDIR/usr/lib/powershell -PSModuleRestore -Runtime linux-x64 -Configuration Release}"

abinfo "Applying temporary workaround"
mv $PKGDIR/usr/lib/Modules $PKGDIR/usr/lib/powershell
mv $PKGDIR/usr/lib/ref $PKGDIR/usr/lib/powershell

mkdir -p "$PKGDIR/usr/bin"
ln -s "/usr/lib/powershell/pwsh" "$PKGDIR/usr/bin/pwsh"
