# Configuration for custom components, template as follows:
#
#   [some-comp]
#   description.default = "Description or pretty name for the component"
#   description.zh_CN = "本地化后的包组简介或名称"
#
# The header (in brackets `[]') is taken as the name of the component.
