#!/bin/bash

set -euo pipefail

# Increase open files limit
#
# Mozilla file functions (OS.File.move()/copy(), NetUtil.asyncFetch/asyncCopy()) can leave file
# descriptors open for a few seconds (even with an explicit inputStream.close() in the case of
# the latter), so a source installation that copies ~500 translators and styles (with fds for
# source and target) can exceed the default 1024 limit.
# Current hard-limit on Ubuntu 16.10 is 4096
ulimit -n 4096

PROGRAM_DIR="$(dirname "$(readlink -f "$0")")"
source "${PROGRAM_DIR}/../../../etc/default/zotero"
"$PROGRAM_DIR/zotero-bin" -app "$PROGRAM_DIR/app/application.ini" "$@"
